import { LegalContent } from '@/components/legal/legal-content';

export default function TermsPage() {
  return (
    <LegalContent title="Terms and Conditions" lastUpdated="9 March 2026">
      <h2>1. Introduction and Agreement</h2>
      <h3>1.1 About These Terms</h3>
      <p>
        These Terms and Conditions (&ldquo;Terms&rdquo;, &ldquo;Legal Terms&rdquo;) constitute a
        legally binding agreement between you (&ldquo;User&rdquo;, &ldquo;you&rdquo;,
        &ldquo;your&rdquo;) and Beckley Electrical, trading as CertMate (&ldquo;CertMate&rdquo;,
        &ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;). These Terms
        govern your access to and use of the CertMate mobile application (&ldquo;App&rdquo;) and all
        related services, features, and content (collectively, the &ldquo;Services&rdquo;).
      </p>

      <h3>1.2 Acceptance</h3>
      <p>
        By downloading, installing, accessing, or using the App, you acknowledge that you have read,
        understood, and agree to be bound by these Terms, our Privacy Policy, and our End User
        Licence Agreement (EULA). If you do not agree to these Terms, you must not use the Services.
      </p>

      <h3>1.3 Eligibility</h3>
      <p>
        You must be at least 18 years of age to use the Services. By using the Services, you
        represent and warrant that: (a) you are at least 18 years of age; (b) you are a qualified
        and competent person within the meaning of the Electricity at Work Regulations 1989; (c) you
        hold valid and adequate professional liability insurance; (d) you have the legal capacity
        and authority to enter into these Terms; (e) all information you provide to us is truthful,
        accurate, and complete.
      </p>

      <h2>2. Description of Services</h2>
      <h3>2.1 What CertMate Does</h3>
      <p>
        CertMate is an AI-assisted productivity tool designed to help qualified UK electricians
        create Electrical Installation Condition Reports (EICRs), Electrical Installation
        Certificates (EICs), and related electrical certification documents. The Services include:
        voice recording and transcription, AI-assisted data extraction, CCU photo analysis,
        certificate generation, and local and cloud data storage.
      </p>

      <h3>2.2 What CertMate Does NOT Do</h3>
      <p>
        The Services are a productivity aid only. CertMate does NOT verify, validate, certify, or
        guarantee the accuracy of any certificate, data, reading, observation, or recommendation. It
        does not replace the professional judgement of a qualified electrician, guarantee compliance
        with BS 7671, or create any professional relationship between CertMate and any third party.
      </p>

      <h2>3. Account Registration and Security</h2>
      <p>
        To use the Services, you must create an account with accurate and complete information. You
        are solely responsible for maintaining the confidentiality of your account credentials. Each
        account is for a single named user only.
      </p>

      <h2>4. AI-Generated Content Disclaimer</h2>
      <p>
        <strong>THIS SECTION IS CRITICAL.</strong> All data, suggestions, calculations,
        observations, and other content generated by the App&apos;s AI features are provided as
        assistance only and are subject to error, inaccuracy, omission, and misinterpretation. ALL
        AI-generated content MUST be thoroughly reviewed, verified, and validated by you before
        being included in any certificate you issue.
      </p>
      <p>
        <strong>
          WE EXPRESSLY DISCLAIM ANY AND ALL RESPONSIBILITY OR LIABILITY FOR ANY INJURY, DEATH, LOSS,
          DAMAGE, CLAIM, PROSECUTION, REGULATORY ACTION, OR ANY OTHER OUTCOME ARISING FROM YOUR
          RELIANCE ON AI-GENERATED CONTENT PROVIDED BY THE SERVICES.
        </strong>
      </p>

      <h2>5. Voice Recording and Audio Processing</h2>
      <p>
        By enabling the recording feature, you consent to audio capture, real-time streaming to
        Deepgram for transcription, processing through Claude Sonnet for data extraction, and
        storage of transcripts. You are solely responsible for obtaining consent from any third
        parties whose voices may be captured.
      </p>

      <h2>6. Professional Responsibility</h2>
      <p>
        You bear full and sole legal responsibility for the accuracy, completeness, compliance, and
        fitness for purpose of all certificates generated using the Services. You must maintain
        valid professional liability insurance at all times.
      </p>

      <h2>7. BS 7671 and Electrical Standards</h2>
      <p>
        Certificate templates are based on model forms in BS 7671:2018 (as amended). CertMate does
        not guarantee compliance with any standard. You must independently verify all certificates
        before issuance.
      </p>

      <h2>8. Payment Terms</h2>
      <p>
        Services are provided on a monthly subscription basis through Apple&apos;s In-App Purchase
        system. Subscriptions auto-renew unless cancelled. No partial refunds for unused portions of
        billing periods.
      </p>

      <h2>9. Intellectual Property</h2>
      <p>
        CertMate owns all rights in the Services. You retain ownership of your data. You may not
        reverse engineer, copy, or create derivative works based on the App.
      </p>

      <h2>10. User Obligations</h2>
      <p>
        You agree to use the Services lawfully and not to generate fraudulent certificates, share
        accounts with unqualified persons, or interfere with the Services.
      </p>

      <h2>11. Third-Party Services</h2>
      <p>
        The Services depend on Deepgram, Anthropic (Claude Sonnet), OpenAI (GPT Vision), AWS, and
        Apple. We are not responsible for the availability or performance of third-party services.
      </p>

      <h2>12. Data Protection and Privacy</h2>
      <p>
        Our collection and use of personal data is governed by our{' '}
        <a href="/legal/privacy" className="text-blue-500 hover:text-blue-600">
          Privacy Policy
        </a>
        . We process data under the UK GDPR and Data Protection Act 2018, as amended by the Data
        (Use and Access) Act 2025.
      </p>

      <h2>13. Limitation of Liability</h2>
      <p>
        Subject to statutory rights under the Consumer Rights Act 2015, our total aggregate
        liability shall not exceed the amount you paid in the 12 months preceding the claim. We
        shall not be liable for indirect, consequential, or special damages.
      </p>

      <h2>14. Disclaimers</h2>
      <p>
        The Services are provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis. We
        make no warranty regarding the accuracy, completeness, or reliability of AI-generated
        content.
      </p>

      <h2>15. Indemnification</h2>
      <p>
        You agree to indemnify CertMate from claims arising from certificates you issue, breach of
        these Terms, or failure to verify AI-generated content.
      </p>

      <h2>16. Termination</h2>
      <p>
        You may terminate at any time through Apple ID settings. We may suspend or terminate your
        account for breach. Certificates previously generated remain your responsibility.
      </p>

      <h2>17. Apple-Specific Terms</h2>
      <p>
        These Terms are between you and CertMate, not Apple. Apple and its subsidiaries are
        third-party beneficiaries of these Terms.
      </p>

      <h2>18. Governing Law</h2>
      <p>
        These Terms are governed by the laws of England and Wales. Disputes are subject to the
        exclusive jurisdiction of the courts of England and Wales.
      </p>

      <h2>19. Modifications</h2>
      <p>
        We reserve the right to change the Services at any time. We do not guarantee uninterrupted
        availability.
      </p>

      <h2>20. General Provisions</h2>
      <p>
        These Terms constitute the entire agreement. If any provision is held invalid, the remaining
        provisions continue in full force.
      </p>

      <h2>21. Contact</h2>
      <p>
        Email:{' '}
        <a href="mailto:support@certmate.co.uk" className="text-blue-500 hover:text-blue-600">
          support@certmate.co.uk
        </a>
      </p>
      <p className="mt-8 font-semibold">
        By using CertMate, you acknowledge that you have read, understood, and agree to be bound by
        these Terms and Conditions.
      </p>
    </LegalContent>
  );
}
