// src/email.js — Email service using Nodemailer
import nodemailer from "nodemailer";
import logger from "../logger.js";

const SMTP_HOST = process.env.SMTP_HOST || "smtp.gmail.com";
const SMTP_PORT = parseInt(process.env.SMTP_PORT || "587");
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;
const FROM_EMAIL = process.env.FROM_EMAIL || "certificates@certmate.uk";

let transporter;

function getTransporter() {
  if (!transporter) {
    if (!SMTP_USER || !SMTP_PASS) {
      logger.warn("Email not configured — SMTP_USER/SMTP_PASS missing");
      return null;
    }
    transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: SMTP_PORT,
      secure: SMTP_PORT === 465,
      auth: { user: SMTP_USER, pass: SMTP_PASS },
    });
  }
  return transporter;
}

export async function sendCertificateEmail({ to, clientName, address, pdfBuffer, pdfFilename, certificateType }) {
  const transport = getTransporter();
  if (!transport) {
    throw new Error("Email not configured — SMTP_USER/SMTP_PASS missing");
  }

  const type = certificateType === "EIC" ? "Electrical Installation Certificate" : "Electrical Installation Condition Report";

  const info = await transport.sendMail({
    from: `"CertMate Certificates" <${FROM_EMAIL}>`,
    to,
    subject: `${type} — ${address}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px;">
        <h2 style="color: #CC0000;">Your ${type} is Ready</h2>
        <p>Dear ${clientName || "Sir/Madam"},</p>
        <p>Please find attached your ${type} for the property at:</p>
        <p style="font-weight: bold; font-size: 16px;">${address}</p>
        <p>If you have any questions about this report, please don't hesitate to contact us.</p>
        <hr style="border: 1px solid #eee;" />
        <p style="color: #888; font-size: 12px;">Generated by CertMate</p>
      </div>
    `,
    attachments: [
      {
        filename: pdfFilename || `${certificateType}_${address}.pdf`,
        content: pdfBuffer,
        contentType: "application/pdf",
      },
    ],
  });

  logger.info("Email sent", { to, messageId: info.messageId, address });
  return true;
}

export async function verifyEmailConfig() {
  const transport = getTransporter();
  if (!transport) return false;
  try {
    await transport.verify();
    return true;
  } catch (err) {
    logger.error("Email config verification failed", { error: err.message });
    return false;
  }
}

export function closeTransporter() {
  if (transporter) {
    transporter.close();
    transporter = null;
  }
}

export function isConfigured() {
  return !!(SMTP_USER && SMTP_PASS);
}
