/**
 * Plan 00C §C5 — handoff-local projections.
 *
 * PLAN-00-EVIDENCE.json / PLAN-00-EVIDENCE.md are DERIVED, non-authoritative
 * local projections of verified S3 object versions — regenerated by the
 * status command beside the handoff, never beside the repo, and NEVER the
 * tracked latency-batch index (a tracked-status write would redeploy and
 * stale the cohort; test-pinned).
 */

import { existsSync, renameSync, writeFileSync } from 'node:fs';
import path from 'node:path';

export function renderEvidenceProjection(fold, { generatedAtIso }) {
  const json = {
    schema_version: 1,
    derived: true,
    note: 'Derived projection of verified S3 object versions — never authoritative.',
    generated_at: generatedAtIso,
    state: fold.state,
    progress: fold.progress,
    stale_deployment: fold.stale_deployment,
    cohort_id: fold.cohort_id,
    stage_a_event: fold.stage_a_event,
    cohort_initialized: fold.cohort_initialized,
    accepted_days: fold.accepted_days,
    day_evaluations: fold.day_evaluations,
    holds: fold.holds,
    blocks: fold.blocks,
    invalid: fold.invalid,
    notes: fold.notes,
  };

  const lines = [];
  lines.push('# Plan 00 evidence — derived projection');
  lines.push('');
  lines.push(`> Generated ${generatedAtIso} from verified S3 object versions. NON-AUTHORITATIVE.`);
  lines.push('');
  lines.push(`- **State:** ${fold.state}${fold.progress ? ` — ${fold.progress}` : ''}`);
  if (fold.stale_deployment) lines.push('- **STALE_DEPLOYMENT** — live runtime does not match the cohort fingerprint.');
  lines.push(`- Cohort: ${fold.cohort_id ?? '(none)'}`);
  lines.push(`- Accepted days: ${fold.accepted_days.length ? fold.accepted_days.join(', ') : 'none'}`);
  lines.push(`- Holds: ${fold.holds.length} · Blocks: ${fold.blocks.length} · Invalid: ${fold.invalid.length}`);
  lines.push('');
  for (const day of fold.day_evaluations) {
    lines.push(`## ${day.day} — ${day.accepted ? 'ACCEPTED' : 'not accepted'}`);
    for (const [req, ok] of Object.entries(day.requirements)) {
      lines.push(`- ${ok ? '✅' : '❌'} ${req}`);
    }
    lines.push('');
  }
  if (fold.blocks.length) {
    lines.push('## Blocks');
    for (const b of fold.blocks) lines.push(`- \`${b.code}\` ${JSON.stringify({ ...b, code: undefined })}`);
    lines.push('');
  }
  lines.push('## Operator commands (the sole post-EP resume/finalisation path)');
  lines.push('');
  lines.push('```bash');
  lines.push('# Publish/verify the Stage-A deployment event (after a green deploy):');
  lines.push('node scripts/plan00-evidence/cli.mjs publish-stage-a --run-id <id> --head-sha <sha>');
  lines.push('# Interactive attestation + cohort initialisation:');
  lines.push('node scripts/plan00-evidence/cli.mjs attest-expectations');
  lines.push(`node scripts/plan00-evidence/cli.mjs init-cohort${fold.cohort_id ? ` --cohort ${fold.cohort_id}` : ''}`);
  lines.push('# Bind a production session / attest a field day:');
  lines.push(`node scripts/plan00-evidence/cli.mjs bind-session --session-id <sid>${fold.cohort_id ? ` --cohort ${fold.cohort_id}` : ''}`);
  lines.push(`node scripts/plan00-evidence/cli.mjs attest-daily --session-ids <sid> --confirmation-session <sid> --confirmation-ref '<op_key>' --heard true --result pass${fold.cohort_id ? ` --cohort ${fold.cohort_id}` : ''}`);
  lines.push(`node scripts/plan00-evidence/cli.mjs attest-dialogue-hearing --session-id <sid> --delivery-ref d:N --heard true --result pass${fold.cohort_id ? ` --cohort ${fold.cohort_id}` : ''}`);
  lines.push('# THE downstream gate (exits non-zero unless DONE against a matching live deployment):');
  lines.push(`node scripts/plan00-evidence/cli.mjs status --exit-nonzero-unless-done${fold.cohort_id ? ` --cohort ${fold.cohort_id}` : ''}`);
  lines.push('```');
  lines.push('');
  if (fold.holds.length) {
    lines.push('## Holds');
    for (const h of fold.holds) lines.push(`- \`${h.code}\` ${JSON.stringify({ ...h, code: undefined, tier: undefined })}`);
    lines.push('');
  }
  return { json, markdown: lines.join('\n') };
}

export function writeProjections(handoffDir, fold, { generatedAtIso }) {
  if (!existsSync(handoffDir)) {
    throw new Error(`handoff directory does not exist: ${handoffDir}`);
  }
  const { json, markdown } = renderEvidenceProjection(fold, { generatedAtIso });
  const jsonPath = path.join(handoffDir, 'PLAN-00-EVIDENCE.json');
  const mdPath = path.join(handoffDir, 'PLAN-00-EVIDENCE.md');
  // Atomic per-file: temp + rename so a crashed writer never leaves a
  // half-written projection (Codex cycle-1).
  const tmpJson = `${jsonPath}.tmp-${process.pid}`;
  const tmpMd = `${mdPath}.tmp-${process.pid}`;
  writeFileSync(tmpJson, `${JSON.stringify(json, null, 2)}\n`);
  writeFileSync(tmpMd, `${markdown}\n`);
  renameSync(tmpJson, jsonPath);
  renameSync(tmpMd, mdPath);
  return { jsonPath, mdPath };
}
