/**
 * WS3 item 2 — read-back dedupe re-key (2026-07-02).
 *
 * Pins the web port of iOS `buildConfirmationDedupeKey`
 * (DeepgramRecordingViewModel.swift:800) byte-for-byte against the
 * backend telemetry mirror `src/extraction/ios-dedupe-key.js`: the
 * literal hash vectors below were generated by executing that module,
 * so a drift in the web djb2 (BigInt UInt64 wrap over Unicode scalars,
 * decimal render) fails here rather than silently de-syncing the
 * client dedupe from the server's `expected_dedupe_key` telemetry.
 *
 * Dedupe OUTCOME tests mirror the session-scoped Set semantics used at
 * the recording-context D6 loop: identical key → suppressed (deduped),
 * distinct keys → both read back. iOS-parity expectations:
 *   - same field+circuit, DIFFERENT text (a correction) → both read back
 *     (id-84 correction-swallow fix — value-aware single-circuit key)
 *   - same field+circuit, SAME text (a genuine duplicate) → DEDUPED
 *   - multi-circuit / board-level with different TEXT → distinct
 *   - identical text → suppressed
 *   - board-scoped isolation via the boardId-in-hash degenerate branch
 */
import { describe, it, expect } from 'vitest';
import {
  buildConfirmationDedupeKey,
  djb2UInt64Decimal,
  DEDUPE_TOKEN_FIELDS,
} from '@/lib/recording/confirmation-dedupe-key';

describe('djb2UInt64Decimal — parity vectors vs src/extraction/ios-dedupe-key.js', () => {
  it('matches the backend mirror on the empty string (djb2 seed)', () => {
    expect(djb2UInt64Decimal('')).toBe('5381');
  });

  it('matches the backend mirror on ASCII text (UInt64 wrap exercised)', () => {
    expect(djb2UInt64Decimal('Circuit 3, Zs 0.44 ohms')).toBe('5652678115008013825');
  });

  it('matches the backend mirror on supplementary-plane input (code points, not UTF-16 units)', () => {
    // Swift iterates unicodeScalars; a UTF-16 code-unit loop would hash
    // the surrogate pair as two values and diverge here.
    expect(djb2UInt64Decimal('a🔌b')).toBe('197715572');
  });

  it('treats null/undefined as "0" (backend mirror contract)', () => {
    expect(djb2UInt64Decimal(null)).toBe('0');
    expect(djb2UInt64Decimal(undefined)).toBe('0');
  });
});

describe('buildConfirmationDedupeKey — branch selection (iOS canon)', () => {
  it('single-circuit uses the VALUE-AWARE "{field}_{circuit}_{djb2(text)}" shape (id-84)', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 5, Zs 0.44 ohms',
        field: 'measured_zs_ohm',
        circuit: 5,
      })
    ).toBe('measured_zs_ohm_5_4307459161827590531');
  });

  it('single-circuit wins over circuits[] when both present', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'whatever',
        field: 'measured_zs_ohm',
        circuit: 2,
        circuits: [2, 3],
      })
    ).toBe('measured_zs_ohm_2_7573094619599403');
  });

  it('multi-circuit broadcast sorts circuits and hashes the spoken text (backend-mirror vector)', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuits 1 to 3, RCD time 24 milliseconds',
        field: 'rcd_time_ms',
        circuit: null,
        circuits: [3, 1, 2],
      })
    ).toBe('rcd_time_ms_1-2-3_10431020094299262130');
  });

  it('degenerate (no circuit info) hashes text + boardId (backend-mirror vectors)', () => {
    expect(
      buildConfirmationDedupeKey({ text: 'SPD BS EN 61643', field: 'spd_bs_en', circuit: null })
    ).toBe('spd_bs_en_3813776636151255864');
    expect(
      buildConfirmationDedupeKey({
        text: 'SPD BS EN 61643',
        field: 'spd_bs_en',
        circuit: null,
        board_id: 'board_2',
      })
    ).toBe('spd_bs_en_4584527826071938513');
  });

  it('missing field falls back to "unknown"', () => {
    expect(buildConfirmationDedupeKey({ text: 'x', circuit: 7 })).toBe('unknown_7_177693');
  });
});

/** Simulate the recording-context D6 session Set: returns which
 *  confirmations would be SPOKEN (not deduped) in arrival order. */
function speakSimulation(confs: Array<Parameters<typeof buildConfirmationDedupeKey>[0]>): number[] {
  const seen = new Set<string>();
  const spoken: number[] = [];
  confs.forEach((conf, i) => {
    const key = buildConfirmationDedupeKey(conf);
    if (seen.has(key)) return;
    seen.add(key);
    spoken.push(i);
  });
  return spoken;
}

describe('dedupe outcomes (session-Set semantics, iOS parity)', () => {
  it('id-84: same field+circuit, DIFFERENT text (a correction) → BOTH read back (value-aware key)', () => {
    expect(
      speakSimulation([
        { text: 'Circuit 3, Zs 0.44 ohms', field: 'measured_zs_ohm', circuit: 3 },
        { text: 'Circuit 3, Zs 0.52 ohms', field: 'measured_zs_ohm', circuit: 3 },
      ])
    ).toEqual([0, 1]);
  });

  it('same field+circuit, SAME text (a genuine duplicate) → second DEDUPED', () => {
    expect(
      speakSimulation([
        { text: 'Circuit 3, Zs 0.44 ohms', field: 'measured_zs_ohm', circuit: 3 },
        { text: 'Circuit 3, Zs 0.44 ohms', field: 'measured_zs_ohm', circuit: 3 },
      ])
    ).toEqual([0]);
  });

  it('same field, DIFFERENT circuit → both read back (2026-06-18 iOS re-key motivation)', () => {
    expect(
      speakSimulation([
        { text: 'Circuit 3, Zs 0.44 ohms', field: 'measured_zs_ohm', circuit: 3 },
        { text: 'Circuit 4, Zs 0.52 ohms', field: 'measured_zs_ohm', circuit: 4 },
      ])
    ).toEqual([0, 1]);
  });

  it('multi-circuit broadcasts with different text → distinct (session C0C21546 turn-9/10 fix)', () => {
    expect(
      speakSimulation([
        { text: 'Circuits 1, 2, RCD time 24', field: 'rcd_time_ms', circuits: [1, 2] },
        { text: 'Circuits 3, 4, RCD time 31', field: 'rcd_time_ms', circuits: [3, 4] },
      ])
    ).toEqual([0, 1]);
  });

  it('board-level same field, different TEXT (value embedded in text) → both read back (session 84CE2125 fix)', () => {
    expect(
      speakSimulation([
        { text: 'Main fuse BS EN 1361', field: 'spd_bs_en' },
        { text: 'Main fuse BS EN 60269', field: 'spd_bs_en' },
      ])
    ).toEqual([0, 1]);
  });

  it('board-level identical text → suppressed (true duplicate)', () => {
    expect(
      speakSimulation([
        { text: 'Main fuse BS EN 1361', field: 'spd_bs_en' },
        { text: 'Main fuse BS EN 1361', field: 'spd_bs_en' },
      ])
    ).toEqual([0]);
  });

  it('board-scoped isolation: same field + same text on different boards → both read back', () => {
    expect(
      speakSimulation([
        { text: 'SPD type 2', field: 'surge_spd_type', board_id: 'board_main' },
        { text: 'SPD type 2', field: 'surge_spd_type', board_id: 'board_garage' },
      ])
    ).toEqual([0, 1]);
  });
});

// ── field-feedback-2026-07-14 §A1a — dedupe_token drift test ──
// Every literal key below was GENERATED by executing the backend mirror
// `src/extraction/ios-dedupe-key.js` (buildPerCircuitDedupeKey /
// buildMultiCircuitDedupeKey / buildDegenerateDedupeKey with the opToken
// argument) — the same vectors are pinned in the Swift twin
// (Tests/CertMateUnifiedTests/Recording/ConfirmationDedupeKeyTests.swift)
// and the backend drift test (src/__tests__/ios-dedupe-key.test.js). A
// change on any side must consciously update all three.
describe('§A1a dedupe_token — allowlist + token-composition vectors (backend-mirror generated)', () => {
  it('the allowlist is EXACTLY the five collision-prone text-op fields', () => {
    expect([...DEDUPE_TOKEN_FIELDS].sort()).toEqual([
      'circuit_designation',
      'circuit_op',
      'field_cleared',
      'observation',
      'observation_deletion',
    ]);
  });

  it('token composition per operation (pinned vectors — mirror to iOS/backend before changing)', () => {
    // designation → turn + operation identity (single-circuit branch)
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 2 named Upstairs lights',
        field: 'circuit_designation',
        circuit: 2,
        dedupe_token: 'desig_2_turn-9',
      })
    ).toBe('circuit_designation_desig_2_turn-9');
    // designation ordinal forms (two designation ops in one turn stay distinct)
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 2 named Sockets',
        field: 'circuit_designation',
        circuit: 2,
        dedupe_token: 'desig_2_turn-9_ord0',
      })
    ).toBe('circuit_designation_desig_2_turn-9_ord0');
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 2 named Sockets',
        field: 'circuit_designation',
        circuit: 2,
        dedupe_token: 'desig_2_turn-9_ord1',
      })
    ).toBe('circuit_designation_desig_2_turn-9_ord1');
    // designation board-scoped (board segment folded into the token by the bundler)
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 1 named Cooker',
        field: 'circuit_designation',
        circuit: 1,
        board_id: 'board-A',
        dedupe_token: 'desig_1_board-A_turn-9',
      })
    ).toBe('circuit_designation_desig_1_board-A_turn-9');
    // clear → {field, circuit, turn, ordinal}
    expect(
      buildConfirmationDedupeKey({
        text: 'R1 plus R2 cleared',
        field: 'field_cleared',
        circuit: 3,
        dedupe_token: 'clear_r1_r2_ohm_3_turn-9_ord0',
      })
    ).toBe('field_cleared_clear_r1_r2_ohm_3_turn-9_ord0');
    // deletion → observation ID (degenerate branch — every deletion is
    // circuit:null + constant text)
    expect(
      buildConfirmationDedupeKey({
        text: 'Observation deleted',
        field: 'observation_deletion',
        dedupe_token: 'obsdel_obs-42',
      })
    ).toBe('observation_deletion_obsdel_obs-42');
    // observation → observation ID
    expect(
      buildConfirmationDedupeKey({
        text: 'Observation C2 — cracked socket',
        field: 'observation',
        dedupe_token: 'obs_obs-7',
      })
    ).toBe('observation_obs_obs-7');
    // rename/circuit op → turn + ordinal + op + ref
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 4 renamed',
        field: 'circuit_op',
        circuit: 4,
        dedupe_token: 'circop_turn-9_0_rename_4',
      })
    ).toBe('circuit_op_circop_turn-9_0_rename_4');
  });

  it('token takes precedence in EVERY branch an allowlisted confirmation can reach', () => {
    // Degenerate branch: identical text, distinct ops → distinct keys
    // (the F7/F10 apology-swallow class killer for deletions).
    const degA = buildConfirmationDedupeKey({
      text: 'Observation deleted',
      field: 'observation_deletion',
      dedupe_token: 'obsdel_a',
    });
    const degB = buildConfirmationDedupeKey({
      text: 'Observation deleted',
      field: 'observation_deletion',
      dedupe_token: 'obsdel_b',
    });
    expect(degA).not.toBe(degB);
    // Multi-circuit branch (grouped designation broadcast).
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuits 1, 2 named Sockets',
        field: 'circuit_designation',
        circuits: [1, 2],
        dedupe_token: 'desig_1-2_turn-9',
      })
    ).toBe('circuit_designation_desig_1-2_turn-9');
  });

  it('replay of ONE operation (same token) → SAME key; F2 regression: two designation ops on one circuit → distinct keys', () => {
    const replay1 = buildConfirmationDedupeKey({
      text: 'Circuit 3 renamed',
      field: 'circuit_op',
      circuit: 3,
      dedupe_token: 'circop_turn-9_0_rename_3',
    });
    const replay2 = buildConfirmationDedupeKey({
      text: 'Circuit 3 renamed',
      field: 'circuit_op',
      circuit: 3,
      dedupe_token: 'circop_turn-9_0_rename_3',
    });
    expect(replay1).toBe(replay2);
    // Two DISTINCT designation writes on the SAME circuit (pre-token both
    // collapsed to 'circuit_designation_2' and the correction read-back
    // was swallowed — session 6B6FE011 F2).
    expect(
      speakSimulation([
        {
          text: 'Circuit 2 named Second floor',
          field: 'circuit_designation',
          circuit: 2,
          dedupe_token: 'desig_2_turn-9',
        },
        {
          text: 'Circuit 2 named Upstairs lights',
          field: 'circuit_designation',
          circuit: 2,
          dedupe_token: 'desig_2_turn-11',
        },
      ])
    ).toEqual([0, 1]);
  });

  it('NEGATIVE: measured-value fields IGNORE the token — VALUE-AWARE key (id-84)', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 1, Zs 0.44 ohms',
        field: 'measured_zs_ohm',
        circuit: 1,
        dedupe_token: 'spurious_token',
      })
    ).toBe('measured_zs_ohm_1_6997897068188437119');
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 2, R1 plus R2 0.86',
        field: 'r1_r2_ohm',
        circuit: 2,
        dedupe_token: 'spurious_token',
      })
    ).toBe('r1_r2_ohm_2_11915183769915549805');
  });

  it('token absent / empty → value-aware single-circuit shape (backward-compatible fallback, backend-first ship order)', () => {
    expect(
      buildConfirmationDedupeKey({ text: 'Circuit 3 renamed', field: 'circuit_op', circuit: 3 })
    ).toBe('circuit_op_3_14649073344730819783');
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 3 renamed',
        field: 'circuit_op',
        circuit: 3,
        dedupe_token: '',
      })
    ).toBe('circuit_op_3_14649073344730819783');
    // Degenerate fallback hashes — generated from the backend mirror.
    expect(
      buildConfirmationDedupeKey({ text: 'Observation deleted', field: 'observation_deletion' })
    ).toBe('observation_deletion_1444582224052499400');
    expect(
      buildConfirmationDedupeKey({
        text: 'Observation deleted',
        field: 'observation_deletion',
        board_id: 'board_2',
      })
    ).toBe('observation_deletion_12155219327966544993');
  });
});

/**
 * A2-multiboard item 10 (2026-07-28) — board identity in the CIRCUIT keys.
 *
 * The degenerate branch has folded `board_id` since W2.3; the two circuit
 * branches never did, and circuit refs are NOT unique across a job. A two-board
 * installation routinely has a circuit 1 on main and a circuit 1 on the garage
 * board; dictate the same field with the same value on both and the spoken
 * lines are character-identical, so the keys collided and the second read-back
 * was silently swallowed (Audio-First #1) even though both writes landed.
 *
 * Every literal below was generated by executing the backend mirror
 * `src/extraction/ios-dedupe-key.js`, exactly as the vectors at the top of this
 * file were. That is the point: the server logs `expected_dedupe_key` from that
 * module, so a divergence here means the telemetry is lying about what this
 * client actually deduped on.
 */
describe('A2-multiboard item 10 — board-aware circuit dedupe keys (backend-mirror vectors)', () => {
  const LINE = 'Circuit 1, Zs 0.55';
  const FANOUT = 'Circuits 1 to 3, Zs 0.55';

  it('THE DEFECT: same field, same ref, same text on DIFFERENT boards → DISTINCT keys', () => {
    const main = buildConfirmationDedupeKey({
      text: LINE,
      field: 'measured_zs_ohm',
      circuit: 1,
      board_id: 'main',
    });
    const garage = buildConfirmationDedupeKey({
      text: LINE,
      field: 'measured_zs_ohm',
      circuit: 1,
      board_id: 'garage',
    });
    expect(main).toBe('measured_zs_ohm_1_12509886869430908783');
    expect(garage).toBe('measured_zs_ohm_1_9569674412376072497');
    expect(main).not.toBe(garage);
  });

  it('DEDUPE OUTCOME: both boards speak; the same board twice does not', () => {
    // The recording-context D6 loop's session Set semantics, in miniature.
    const spoken = new Set<string>();
    const speak = (board: string) => {
      const key = buildConfirmationDedupeKey({
        text: LINE,
        field: 'measured_zs_ohm',
        circuit: 1,
        board_id: board,
      });
      if (spoken.has(key)) return false;
      spoken.add(key);
      return true;
    };
    expect(speak('main')).toBe(true);
    expect(speak('garage')).toBe(true); // pre-item-10 this was FALSE — swallowed
    expect(speak('garage')).toBe(false); // a true duplicate still dedupes
  });

  it('BYTE-IDENTICAL: no board id hashes exactly as pre-item-10 (text alone)', () => {
    const noBoard = buildConfirmationDedupeKey({
      text: LINE,
      field: 'measured_zs_ohm',
      circuit: 1,
    });
    expect(noBoard).toBe('measured_zs_ohm_1_3803995004801192586');
    expect(noBoard).toBe(`measured_zs_ohm_1_${djb2UInt64Decimal(LINE)}`);
    // An explicit null `board_id` is the same as omitting the key.
    expect(
      buildConfirmationDedupeKey({
        text: LINE,
        field: 'measured_zs_ohm',
        circuit: 1,
        board_id: null,
      })
    ).toBe(noBoard);
  });

  it('MULTI-CIRCUIT: a fan-out on two boards is distinct; boardless is unchanged', () => {
    const main = buildConfirmationDedupeKey({
      text: FANOUT,
      field: 'measured_zs_ohm',
      circuits: [1, 2, 3],
      board_id: 'main',
    });
    const garage = buildConfirmationDedupeKey({
      text: FANOUT,
      field: 'measured_zs_ohm',
      circuits: [1, 2, 3],
      board_id: 'garage',
    });
    expect(main).toBe('measured_zs_ohm_1-2-3_11373077424483400792');
    expect(garage).toBe('measured_zs_ohm_1-2-3_7516041803079828570');
    expect(main).not.toBe(garage);

    const noBoard = buildConfirmationDedupeKey({
      text: FANOUT,
      field: 'measured_zs_ohm',
      circuits: [1, 2, 3],
    });
    expect(noBoard).toBe('measured_zs_ohm_1-2-3_16967602662836620019');
    expect(noBoard).toBe(`measured_zs_ohm_1-2-3_${djb2UInt64Decimal(FANOUT)}`);
  });

  it('GATE INTACT: a same-board correction still speaks (value-awareness preserved)', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 1, Zs 0.83',
        field: 'measured_zs_ohm',
        circuit: 1,
        board_id: 'main',
      })
    ).not.toBe(
      buildConfirmationDedupeKey({
        text: 'Circuit 1, Zs 0.63',
        field: 'measured_zs_ohm',
        circuit: 1,
        board_id: 'main',
      })
    );
  });

  it('TOKEN PRECEDENCE UNCHANGED: an allowlisted text-op ignores the board id', () => {
    // The token IS the operation identity and already distinguishes two renames
    // on two boards; folding a board id in would break §A1a replay stability.
    const withToken = (board: string) =>
      buildConfirmationDedupeKey({
        text: 'Circuit 1 renamed',
        field: 'circuit_op',
        circuit: 1,
        board_id: board,
        dedupe_token: 'rename_c1_t7_ord0',
      });
    expect(withToken('main')).toBe(withToken('garage'));
    expect(withToken('main')).toBe('circuit_op_rename_c1_t7_ord0');
  });
});
