/**
 * WS3 item 2 — read-back dedupe re-key (2026-07-02).
 *
 * Pins the web port of iOS `buildConfirmationDedupeKey`
 * (DeepgramRecordingViewModel.swift:800) byte-for-byte against the
 * backend telemetry mirror `src/extraction/ios-dedupe-key.js`: the
 * literal hash vectors below were generated by executing that module,
 * so a drift in the web djb2 (BigInt UInt64 wrap over Unicode scalars,
 * decimal render) fails here rather than silently de-syncing the
 * client dedupe from the server's `expected_dedupe_key` telemetry.
 *
 * Dedupe OUTCOME tests mirror the session-scoped Set semantics used at
 * the recording-context D6 loop: identical key → suppressed (deduped),
 * distinct keys → both read back. iOS-parity expectations:
 *   - same field+circuit twice → DEDUPED (do NOT expect two read-backs;
 *     corrections ride the separate correction-TTS path)
 *   - multi-circuit / board-level with different TEXT → distinct
 *   - identical text → suppressed
 *   - board-scoped isolation via the boardId-in-hash degenerate branch
 */
import { describe, it, expect } from 'vitest';
import {
  buildConfirmationDedupeKey,
  djb2UInt64Decimal,
} from '@/lib/recording/confirmation-dedupe-key';

describe('djb2UInt64Decimal — parity vectors vs src/extraction/ios-dedupe-key.js', () => {
  it('matches the backend mirror on the empty string (djb2 seed)', () => {
    expect(djb2UInt64Decimal('')).toBe('5381');
  });

  it('matches the backend mirror on ASCII text (UInt64 wrap exercised)', () => {
    expect(djb2UInt64Decimal('Circuit 3, Zs 0.44 ohms')).toBe('5652678115008013825');
  });

  it('matches the backend mirror on supplementary-plane input (code points, not UTF-16 units)', () => {
    // Swift iterates unicodeScalars; a UTF-16 code-unit loop would hash
    // the surrogate pair as two values and diverge here.
    expect(djb2UInt64Decimal('a🔌b')).toBe('197715572');
  });

  it('treats null/undefined as "0" (backend mirror contract)', () => {
    expect(djb2UInt64Decimal(null)).toBe('0');
    expect(djb2UInt64Decimal(undefined)).toBe('0');
  });
});

describe('buildConfirmationDedupeKey — branch selection (iOS canon)', () => {
  it('single-circuit keeps the legacy "{field}_{circuit}" shape (correction-TTS cross-match)', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuit 5, Zs 0.44 ohms',
        field: 'measured_zs_ohm',
        circuit: 5,
      })
    ).toBe('measured_zs_ohm_5');
  });

  it('single-circuit wins over circuits[] when both present', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'whatever',
        field: 'measured_zs_ohm',
        circuit: 2,
        circuits: [2, 3],
      })
    ).toBe('measured_zs_ohm_2');
  });

  it('multi-circuit broadcast sorts circuits and hashes the spoken text (backend-mirror vector)', () => {
    expect(
      buildConfirmationDedupeKey({
        text: 'Circuits 1 to 3, RCD time 24 milliseconds',
        field: 'rcd_time_ms',
        circuit: null,
        circuits: [3, 1, 2],
      })
    ).toBe('rcd_time_ms_1-2-3_10431020094299262130');
  });

  it('degenerate (no circuit info) hashes text + boardId (backend-mirror vectors)', () => {
    expect(
      buildConfirmationDedupeKey({ text: 'SPD BS EN 61643', field: 'spd_bs_en', circuit: null })
    ).toBe('spd_bs_en_3813776636151255864');
    expect(
      buildConfirmationDedupeKey({
        text: 'SPD BS EN 61643',
        field: 'spd_bs_en',
        circuit: null,
        board_id: 'board_2',
      })
    ).toBe('spd_bs_en_4584527826071938513');
  });

  it('missing field falls back to "unknown"', () => {
    expect(buildConfirmationDedupeKey({ text: 'x', circuit: 7 })).toBe('unknown_7');
  });
});

/** Simulate the recording-context D6 session Set: returns which
 *  confirmations would be SPOKEN (not deduped) in arrival order. */
function speakSimulation(confs: Array<Parameters<typeof buildConfirmationDedupeKey>[0]>): number[] {
  const seen = new Set<string>();
  const spoken: number[] = [];
  confs.forEach((conf, i) => {
    const key = buildConfirmationDedupeKey(conf);
    if (seen.has(key)) return;
    seen.add(key);
    spoken.push(i);
  });
  return spoken;
}

describe('dedupe outcomes (session-Set semantics, iOS parity)', () => {
  it('same field+circuit twice → second DEDUPED even with different text (iOS single-circuit shape)', () => {
    expect(
      speakSimulation([
        { text: 'Circuit 3, Zs 0.44 ohms', field: 'measured_zs_ohm', circuit: 3 },
        { text: 'Circuit 3, Zs 0.52 ohms', field: 'measured_zs_ohm', circuit: 3 },
      ])
    ).toEqual([0]);
  });

  it('same field, DIFFERENT circuit → both read back (2026-06-18 iOS re-key motivation)', () => {
    expect(
      speakSimulation([
        { text: 'Circuit 3, Zs 0.44 ohms', field: 'measured_zs_ohm', circuit: 3 },
        { text: 'Circuit 4, Zs 0.52 ohms', field: 'measured_zs_ohm', circuit: 4 },
      ])
    ).toEqual([0, 1]);
  });

  it('multi-circuit broadcasts with different text → distinct (session C0C21546 turn-9/10 fix)', () => {
    expect(
      speakSimulation([
        { text: 'Circuits 1, 2, RCD time 24', field: 'rcd_time_ms', circuits: [1, 2] },
        { text: 'Circuits 3, 4, RCD time 31', field: 'rcd_time_ms', circuits: [3, 4] },
      ])
    ).toEqual([0, 1]);
  });

  it('board-level same field, different TEXT (value embedded in text) → both read back (session 84CE2125 fix)', () => {
    expect(
      speakSimulation([
        { text: 'Main fuse BS EN 1361', field: 'spd_bs_en' },
        { text: 'Main fuse BS EN 60269', field: 'spd_bs_en' },
      ])
    ).toEqual([0, 1]);
  });

  it('board-level identical text → suppressed (true duplicate)', () => {
    expect(
      speakSimulation([
        { text: 'Main fuse BS EN 1361', field: 'spd_bs_en' },
        { text: 'Main fuse BS EN 1361', field: 'spd_bs_en' },
      ])
    ).toEqual([0]);
  });

  it('board-scoped isolation: same field + same text on different boards → both read back', () => {
    expect(
      speakSimulation([
        { text: 'SPD type 2', field: 'surge_spd_type', board_id: 'board_main' },
        { text: 'SPD type 2', field: 'surge_spd_type', board_id: 'board_garage' },
      ])
    ).toEqual([0, 1]);
  });
});
