/**
 * Plan 00B-3 C0 — the executable derivability contract.
 *
 * An 00C-style builder consuming ONLY the five-key allowlisted completion
 * snapshot must reconstruct the complete family evidence the 00C fold
 * consumes. The contract is pinned three ways:
 *   1. SCHEMA drift — the code registry/enums byte-agree with the
 *      pre-authored schema artifact (authored BEFORE implementation).
 *   2. TWO-SIDED FIXTURE — hand-authored snapshot fixtures deep-equal their
 *      hand-computed expected projections (never generated by the projector
 *      under test).
 *   3. LIVE COMPOSITION — sessions composed through the REAL lifecycle
 *      hooks/ledgers satisfy the three-way agreement invariant: the
 *      latched-snapshot reconstruction and the frozen-ledger projection
 *      agree (comparable subset), across accepted AND rejected ask
 *      transitions, deliveries, playbacks, invalid state and round usage.
 *
 * The four open cycle-5 findings of the 00B-2 hold are MANDATORY NAMED
 * CASES here (proven RED against the branch tip before their fixes landed —
 * recorded in the execution log):
 *   F1 — rejected ask transitions must not publish as valid lifecycle
 *        evidence (acceptance-gated sub-records, C1);
 *   F2 — open Tier-2 asks must hold the completion freeze (C2);
 *   F3 — delivery/playback rows must carry the SEMANTIC family with
 *        transport as a separate field (C3);
 *   F4 — lives in plan00-frame-parity-matrix.test.js (observation
 *        update/recode scenario legs).
 * C5's projection fields (api_transport, delivery refs/aliases, ACK-body
 * hashes, freeze-time invalid rows, the unconsumed-provisional fold) are
 * asserted here as further contract cases.
 */

import { describe, test, expect } from '@jest/globals';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  normaliseEvaluationContext,
  attachEvaluationContext,
  freezeEvidenceCompletion,
  getCompletionFreeze,
  readInFlightCounts,
  getLifecycleLedger,
} from '../extraction/plan00-lifecycle-hooks.js';
import {
  createAskLedger,
  createDeliveryLedger,
  buildLiveAskKey,
} from '../extraction/plan00-audibility-ledgers.js';
import { createMutationObserver } from '../extraction/plan00-semantic-capture.js';
import {
  ASK_QUIESCENCE_FAMILIES,
  SEMANTIC_FAMILIES,
  EVIDENCE_TRANSPORTS,
  PRODUCER_REGISTRY,
  NON_PRODUCER_ROW_KINDS,
  PRODUCER_ROW_KINDS,
  STOP_BOUNDARY_TERMINALS,
  NON_QUIESCENT_TERMINALS,
  REJECTION_REASONS,
} from '../extraction/plan00-evidence-registry.js';
import {
  buildEvidenceProjectionV1,
  projectFrozenLedgersV1,
  comparableSubset,
} from '../extraction/plan00-evidence-projection.js';
import { attributeRoundUsage } from '../extraction/round-usage-attribution.js';
import { SEMANTIC_ORACLE_INPUTS } from '../../scripts/model-ab/lib/expectation-projection.mjs';
import { composeCaptureInvalid } from '../../scripts/model-ab/lib/semantic-judge.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const contractDir = path.join(
  repoRoot,
  'tests',
  'fixtures',
  'test-contracts',
  'plan00-evidence-contract'
);
const loadJson = (name) => JSON.parse(fs.readFileSync(path.join(contractDir, name), 'utf8'));

const schema = loadJson('schema-v1.json');
const snapshotA = loadJson('snapshot-v1.json');
const projectionA = loadJson('projection-v1.json');
const snapshotB = loadJson('snapshot-ineligible-v1.json');
const projectionB = loadJson('projection-ineligible-v1.json');
const ackSequences = loadJson('ack-sequences-v1.json');

const stripComment = ({ _comment, ...rest }) => rest;

function makeEntry() {
  return {
    session: { costTracker: { inFlightBillableInvocationCount: 0, usageRevision: 0 } },
  };
}

function composeCtx(entry, { sessionId = 'sess_contract' } = {}) {
  const ctx = normaliseEvaluationContext(
    {
      observer: {
        buildCandidate: (snap) => snap,
        publish: () => {},
      },
      mutationObserver: createMutationObserver({ sessionId }),
      askLedger: createAskLedger(),
      deliveryLedger: createDeliveryLedger(),
    },
    { sessionId }
  );
  attachEvaluationContext(entry, ctx);
  return ctx;
}

const K = (n) =>
  buildLiveAskKey({
    origin: 'contract',
    purpose: `p_${n}`,
    reason: null,
    contextField: null,
    boardId: null,
    circuits: [],
    expectedAnswerShape: 'number',
    observationClarificationKind: null,
    pendingWrite: null,
    chainRole: null,
  });

const subRecords = (entry) => getLifecycleLedger(entry).subRecords;
const rowsOfKind = (entry, kind) => subRecords(entry).filter((r) => r.kind === kind);

// ── 1. Schema drift — code registry vs the pre-authored schema ─────────────

describe('contract schema drift (C0 anti-shaping)', () => {
  test('snapshot key allowlist matches', () => {
    expect(schema.snapshot_keys).toEqual([
      'sessionId',
      'boundary',
      'counts',
      'revisions',
      'sub_records',
    ]);
  });

  test('ask-quiescence families, semantic families and transports byte-agree', () => {
    expect([...ASK_QUIESCENCE_FAMILIES]).toEqual(schema.ask_quiescence_families);
    expect([...SEMANTIC_FAMILIES]).toEqual(schema.semantic_families);
    expect([...EVIDENCE_TRANSPORTS]).toEqual(schema.transports);
  });

  test('the producer registry byte-agrees with the schema (both directions)', () => {
    const codeIds = Object.keys(PRODUCER_REGISTRY).sort();
    const schemaIds = Object.keys(schema.producer_registry).sort();
    expect(codeIds).toEqual(schemaIds);
    for (const id of codeIds) {
      expect({ ...PRODUCER_REGISTRY[id] }).toEqual(schema.producer_registry[id]);
    }
  });

  test('non-producer row-kind allowlist byte-agrees', () => {
    expect([...NON_PRODUCER_ROW_KINDS]).toEqual(schema.non_producer_row_kinds);
  });

  test('stop-boundary terminal set byte-agrees', () => {
    expect([...STOP_BOUNDARY_TERMINALS]).toEqual(schema.ask_terminals.stop_boundary_non_quiescent);
  });

  test('the NON-quiescent terminal set (stop boundary + unknown_terminal) byte-agrees', () => {
    expect([...NON_QUIESCENT_TERMINALS]).toEqual(schema.ask_terminals.non_quiescent_terminals);
  });

  test('the code rejection-regime table byte-agrees with the schema (both directions)', () => {
    const codeReasons = Object.keys(REJECTION_REASONS).sort();
    const schemaReasons = Object.keys(schema.rejection_reasons).sort();
    expect(codeReasons).toEqual(schemaReasons);
    for (const reason of codeReasons) {
      const code = REJECTION_REASONS[reason];
      const spec = schema.rejection_reasons[reason];
      expect({ reason, ...code }).toEqual({
        reason,
        source_ledger: spec.source_ledger,
        regime: spec.regime,
        row_kind: spec.row_kind ?? null,
      });
    }
  });

  test('every row kind is either a producer row kind or an allowlisted non-producer kind', () => {
    const all = new Set([...PRODUCER_ROW_KINDS, ...NON_PRODUCER_ROW_KINDS]);
    expect([...all].sort()).toEqual(Object.keys(schema.row_kinds).sort());
  });

  test('null semantic_family is legal ONLY for event_class ask (table over the registry)', () => {
    for (const [id, entry] of Object.entries(PRODUCER_REGISTRY)) {
      if (entry.event_class === 'ask') {
        expect({ id, semantic_family: entry.semantic_family }).toEqual({
          id,
          semantic_family: null,
        });
        expect(ASK_QUIESCENCE_FAMILIES).toContain(entry.quiescence_family);
      } else {
        expect(SEMANTIC_FAMILIES).toContain(entry.semantic_family);
        expect(entry.quiescence_family).toBeNull();
      }
      expect(EVIDENCE_TRANSPORTS).toContain(entry.transport);
    }
  });

  test('every semantic family has at least one producer (reverse exhaustiveness, unscoped)', () => {
    for (const family of SEMANTIC_FAMILIES) {
      const producers = Object.values(PRODUCER_REGISTRY).filter(
        (e) => e.semantic_family === family
      );
      expect(producers.length).toBeGreaterThan(0);
    }
  });

  test('the rejection-reason vocabulary is closed and regime-classified', () => {
    for (const [reason, spec] of Object.entries(schema.rejection_reasons)) {
      expect(['structural_latch', 'transition_rejection', 'pre_admission']).toContain(spec.regime);
      expect(['ask', 'delivery']).toContain(spec.source_ledger);
      // pre-admission reasons are telemetry: NO row kind by definition
      if (spec.regime === 'pre_admission') {
        expect(spec.row_kind).toBeNull();
      } else {
        expect(typeof spec.row_kind).toBe('string');
      }
      // the ONE transition rejection is the sanctioned no-latch reason
      if (spec.regime === 'transition_rejection') {
        expect(reason).toBe('answered_without_full_proof');
        expect(spec.no_invalid_latch).toBe(true);
        expect(spec.entry_stays_open).toBe(true);
      }
    }
  });
});

// ── 2. Fixture rows validate against the schema ────────────────────────────

describe('fixture validation against schema-v1 (C0)', () => {
  const validateSnapshot = (snap) => {
    const body = stripComment(snap);
    expect(Object.keys(body).sort()).toEqual([...schema.snapshot_keys].sort());
    for (const row of body.sub_records) {
      const kindSpec = schema.row_kinds[row.kind];
      expect(kindSpec).toBeDefined();
      // no spoken text on ANY sub-record (00C manifest PII rule)
      expect(Object.prototype.hasOwnProperty.call(row, 'text')).toBe(false);
      if (row.producer_id != null) {
        const producer = PRODUCER_REGISTRY[row.producer_id];
        expect(producer).toBeDefined();
        if (row.semantic_family != null) {
          expect(row.semantic_family).toBe(producer.semantic_family);
        }
        if (row.transport != null && row.kind !== 'delivery_rejected') {
          expect(row.transport).toBe(producer.transport);
        }
      }
      if (row.kind === 'ask_lifecycle') {
        expect(ASK_QUIESCENCE_FAMILIES).toContain(row.family);
      }
      if (row.kind === 'ask_transition_rejected' && row.family !== null) {
        // schema: family is nullable on rejected rows (unresolvable binding)
        expect(ASK_QUIESCENCE_FAMILIES).toContain(row.family);
      }
      if (
        row.kind === 'ask_transition_rejected' ||
        row.kind === 'delivery_rejected' ||
        row.kind === 'playback_rejected'
      ) {
        expect(Object.keys(schema.rejection_reasons)).toContain(row.reason);
      }
      if (row.kind === 'freeze_invalid') {
        expect([
          'ask_invalid',
          'delivery_invalid',
          'producer_invalid',
          'mutation_invalid',
          'delivery_prepared_outstanding',
        ]).toContain(row.condition);
      }
      if (row.kind === 'round_usage') {
        const allow = new Set([
          ...schema.row_kinds.round_usage.fields.allowlist,
          'kind',
          'revision',
        ]);
        for (const key of Object.keys(row)) expect(allow.has(key)).toBe(true);
      }
    }
  };

  test('fixture A (eligible) validates', () => validateSnapshot(snapshotA));
  test('fixture B (ineligible) validates', () => validateSnapshot(snapshotB));
});

// ── 3. The two-sided committed artifact ────────────────────────────────────

describe('two-sided fixture (C0)', () => {
  test('fixture A: the five-key snapshot reconstructs the complete eligible projection', () => {
    expect(buildEvidenceProjectionV1(stripComment(snapshotA))).toEqual(stripComment(projectionA));
  });

  test('fixture B: the ineligible projection carries the named rejected case, freeze rows and zero credit', () => {
    expect(buildEvidenceProjectionV1(stripComment(snapshotB))).toEqual(stripComment(projectionB));
  });

  test('fixture B named case composition: rejected resolution visible, uncreditable, non-quiescent', () => {
    const proj = buildEvidenceProjectionV1(stripComment(snapshotB));
    // visible as a rejection…
    expect(proj.ask_families.dialogue_script.rejected).toEqual([
      {
        stage_attempted: 'resolved',
        reason: 'answered_without_full_proof',
        terminal_attempted: 'answered',
        runtime_id: 'srv_rej_1',
      },
    ]);
    // …grants ZERO resolved credit…
    expect(proj.ask_families.dialogue_script.resolved_terminals).toEqual({});
    // …prevents the family gate…
    expect(proj.family_gates.dialogue_script.ask_lifecycle_complete).toBe(false);
    // …and the ask counts non-quiescent.
    expect(proj.open_asks.dialogue_script).toBe(1);
    expect(proj.quiescence.non_quiescent_at_stop).toBe(1);
  });
});

// ── 4. Contract cases through the REAL hooks (the four findings + C5) ──────

describe('F1 (C1) — acceptance-gated sub-records', () => {
  test('a rejected answered resolution appends ONLY the rejected audit row, no latch, entry stays open', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_1',
      liveAskKey: K(1),
    });
    ctx.recordAskEmitted({ runtimeId: 'srv_1' });
    // §B3 full proof missing: transcript never resolved
    ctx.recordAskResolved({
      runtimeId: 'srv_1',
      terminal: 'answered',
      detail: { answer_frame_id: 'srv_1', transcript_resolved: false },
    });
    const lifecycle = rowsOfKind(entry, 'ask_lifecycle');
    expect(lifecycle.map((r) => r.stage)).toEqual(['produced', 'emitted']);
    const rejected = rowsOfKind(entry, 'ask_transition_rejected');
    expect(rejected).toHaveLength(1);
    expect(rejected[0]).toMatchObject({
      family: 'dialogue_script',
      stage_attempted: 'resolved',
      terminal_attempted: 'answered',
      reason: 'answered_without_full_proof',
      runtime_id: 'srv_1',
    });
    // sanctioned ledger change: NO invalid latch, entry remains 'emitted'
    expect(ctx.askLedger.invalid).toBeNull();
    expect(ctx.askLedger.entries[0].state).toBe('emitted');
    // and the session cannot freeze eligible past it
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_f1',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(false);
    expect(frozen.counts.open_asks_dialogue_script).toBe(1);
  });

  test('an accepted answered resolution appends exactly one resolved row (mutual exclusion)', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.recordAskProduced({ producerId: 'dispatcher_ask', runtimeId: 'toolu_1', liveAskKey: K(2) });
    ctx.recordAskEmitted({ runtimeId: 'toolu_1' });
    ctx.recordAskResolved({
      runtimeId: 'toolu_1',
      terminal: 'answered',
      detail: { answer_frame_id: 'toolu_1', transcript_resolved: true },
    });
    const lifecycle = rowsOfKind(entry, 'ask_lifecycle');
    expect(lifecycle.map((r) => r.stage)).toEqual(['produced', 'emitted', 'resolved']);
    expect(lifecycle[2].terminal).toBe('answered');
    expect(rowsOfKind(entry, 'ask_transition_rejected')).toHaveLength(0);
    expect(ctx.askLedger.invalid).toBeNull();
  });

  test('a structural rejection latches invalid AND appends the rejected audit row', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.recordAskResolved({
      runtimeId: 'toolu_ghost',
      terminal: 'answered',
      detail: { answer_frame_id: 'toolu_ghost', transcript_resolved: true },
    });
    const rejected = rowsOfKind(entry, 'ask_transition_rejected');
    expect(rejected).toHaveLength(1);
    expect(rejected[0].reason).toBe('resolution_without_emitted');
    expect(ctx.askLedger.invalid?.reason).toBe('resolution_without_emitted');
    // structural latch surfaces as a freeze-time row (C5)
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_f1s',
      boundary: 'session_stopped',
    });
    const freezeRows = frozen.evidence.sub_records.filter((r) => r.kind === 'freeze_invalid');
    expect(freezeRows).toEqual([
      expect.objectContaining({ condition: 'ask_invalid', reason: 'resolution_without_emitted' }),
    ]);
  });

  test('every attempted transition yields exactly one row (one-attempt→one-row invariant)', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_a',
      liveAskKey: K(3),
    });
    ctx.recordAskEmitted({ runtimeId: 'srv_a' });
    // duplicate produced binding — structural rejection, one row
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_a',
      liveAskKey: K(3),
    });
    // rejected resolution — one row
    ctx.recordAskResolved({
      runtimeId: 'srv_a',
      terminal: 'answered',
      detail: { answer_frame_id: 'srv_OTHER', transcript_resolved: true },
    });
    // accepted terminal — one row
    ctx.recordAskResolved({ runtimeId: 'srv_a', terminal: 'timeout', detail: {} });
    const attempts =
      rowsOfKind(entry, 'ask_lifecycle').length +
      rowsOfKind(entry, 'ask_transition_rejected').length;
    // produced + emitted + duplicate-produced-rejected + rejected-answered + timeout
    expect(attempts).toBe(5);
  });
});

describe('F2 (C2) — Tier-2 ask quiescence', () => {
  const PRODUCERS = {
    dispatcher: 'dispatcher_ask',
    dialogue_script: 'dialogue_script_ask',
    address_mirror: 'address_mirror_ask',
  };

  test.each(ASK_QUIESCENCE_FAMILIES)(
    'an emitted-but-unresolved %s ask holds the completion freeze ineligible',
    (family) => {
      const entry = makeEntry();
      const ctx = composeCtx(entry);
      ctx.recordAskProduced({
        producerId: PRODUCERS[family],
        runtimeId: `rt_${family}`,
        liveAskKey: K(family),
      });
      ctx.recordAskEmitted({ runtimeId: `rt_${family}` });
      const counts = readInFlightCounts(entry);
      expect(counts[`open_asks_${family}`]).toBe(1);
      const frozen = freezeEvidenceCompletion(entry, {
        sessionId: `sess_${family}`,
        boundary: 'session_stopped',
      });
      expect(frozen.eligible).toBe(false);
      expect(frozen.reason).toBe('non_quiescent_at_stop');
      expect(frozen.counts[`open_asks_${family}`]).toBe(1);
    }
  );

  test.each(ASK_QUIESCENCE_FAMILIES)(
    'stop-race, %s: a post-freeze resolution can never flip the latched ineligible freeze',
    (family) => {
      const entry = makeEntry();
      const ctx = composeCtx(entry);
      ctx.recordAskProduced({
        producerId: PRODUCERS[family],
        runtimeId: `rt2_${family}`,
        liveAskKey: K(`2${family}`),
      });
      ctx.recordAskEmitted({ runtimeId: `rt2_${family}` });
      const frozen = freezeEvidenceCompletion(entry, {
        sessionId: `sess2_${family}`,
        boundary: 'session_stopped',
      });
      expect(frozen.eligible).toBe(false);
      // late resolution after the freeze
      ctx.recordAskResolved({
        runtimeId: `rt2_${family}`,
        terminal: 'answered',
        detail: { answer_frame_id: `rt2_${family}`, transcript_resolved: true },
      });
      expect(getCompletionFreeze(entry)).toBe(frozen);
      expect(getCompletionFreeze(entry).eligible).toBe(false);
    }
  );

  test.each(ASK_QUIESCENCE_FAMILIES)(
    'stop-race, %s: a STOP-BOUNDARY terminal still counts non-quiescent (stop-expiry cannot launder openness)',
    (family) => {
      const entry = makeEntry();
      const ctx = composeCtx(entry);
      ctx.recordAskProduced({
        producerId: PRODUCERS[family],
        runtimeId: `rt3_${family}`,
        liveAskKey: K(`3${family}`),
      });
      ctx.recordAskEmitted({ runtimeId: `rt3_${family}` });
      // stop-expiry resolves the entry BEFORE the freeze reads counts
      ctx.recordAskResolved({
        runtimeId: `rt3_${family}`,
        terminal: 'session_stopped',
        detail: {},
      });
      const counts = readInFlightCounts(entry);
      expect(counts[`open_asks_${family}`]).toBe(1);
      const frozen = freezeEvidenceCompletion(entry, {
        sessionId: `sess3_${family}`,
        boundary: 'session_stopped',
      });
      expect(frozen.eligible).toBe(false);
    }
  );

  test('a pre-stop terminal (timeout) closes the entry as quiescence-compatible', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.recordAskProduced({ producerId: 'dispatcher_ask', runtimeId: 'rt_t', liveAskKey: K('t') });
    ctx.recordAskEmitted({ runtimeId: 'rt_t' });
    ctx.recordAskResolved({ runtimeId: 'rt_t', terminal: 'timeout', detail: {} });
    expect(readInFlightCounts(entry).open_asks_dispatcher).toBe(0);
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_t',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(true);
  });
});

describe('F3 (C3) — semantic family + transport on delivery and playback rows', () => {
  test('delivery rows carry producer_id, semantic_family and transport as separate fields', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    const op = {
      extractionTurnId: 't1',
      field: 'measured_zs_ohm',
      circuit: 4,
      boardId: null,
      ordinal: 0,
    };
    ctx.recordDelivery([op], {
      producerId: 'dialogue_confirmation',
      kind: 'dialogue_confirmation',
    });
    const rows = rowsOfKind(entry, 'delivery_evidence');
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({
      producer_id: 'dialogue_confirmation',
      semantic_family: 'dialogue_script',
      transport: 'dialogue_ws',
      delivery_kind: 'dialogue_confirmation',
    });
    // C5 — stable replay-stable delivery ref + ledger sequence
    expect(rows[0].at_seq).toBe(1);
    expect(rows[0].delivery_ref).toBe('d:1');
    // no overloaded legacy `family` key
    expect(Object.prototype.hasOwnProperty.call(rows[0], 'family')).toBe(false);
  });

  test('playback rows carry producer_id, semantic_family, transport, source and ACK-body hash', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    const op = {
      extractionTurnId: 't2',
      field: 'r1_r2_ohm',
      circuit: 7,
      boardId: null,
      ordinal: 0,
    };
    ctx.recordDelivery([op], { producerId: 'result_frame_confirmation', kind: 'confirmation' });
    const row = ctx.recordPlayback({ ok: true, turn: 't2' }, [op], {
      producerId: 'playback_ack_slot',
      source: 'ordinary',
    });
    expect(row).toBeTruthy();
    const rows = rowsOfKind(entry, 'playback_evidence');
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({
      producer_id: 'playback_ack_slot',
      semantic_family: 'ordinary_confirmation',
      transport: 'http_playback_ack',
      source: 'ordinary',
    });
    expect(typeof rows[0].ack_body_hash).toBe('string');
    expect(rows[0].ack_body_hash).toHaveLength(64);
  });

  test('an unknown producer id appends an uncreditable producer_unknown row and invalidates the owning ledger', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.recordDelivery(
      [{ extractionTurnId: 't3', field: 'x', circuit: null, boardId: null, ordinal: 0 }],
      {
        producerId: 'not_a_producer',
        kind: 'confirmation',
      }
    );
    const unknown = rowsOfKind(entry, 'producer_unknown');
    expect(unknown).toHaveLength(1);
    expect(unknown[0]).toMatchObject({
      event_class: 'delivery',
      producer_id_raw: 'not_a_producer',
    });
    expect(ctx.deliveryLedger.invalid?.reason).toBe('unknown_producer_id');
    expect(rowsOfKind(entry, 'delivery_evidence')).toHaveLength(0);

    ctx.recordAskProduced({ producerId: 'nope_ask', runtimeId: 'rt_u', liveAskKey: K('u') });
    expect(ctx.askLedger.invalid?.reason).toBe('unknown_producer_id');
    expect(rowsOfKind(entry, 'producer_unknown')).toHaveLength(2);
  });
});

describe('C1 ternary — idempotent and pre-admission playback verdicts', () => {
  test('a byte-identical ACK retransmission yields ONE authoritative row plus ONE idempotent audit row', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    const op = {
      extractionTurnId: 't4',
      field: 'measured_zs_ohm',
      circuit: 9,
      boardId: null,
      ordinal: 0,
    };
    ctx.recordDelivery([op], { producerId: 'result_frame_confirmation', kind: 'confirmation' });
    const ack = { ok: true, turn: 't4', seq: 1 };
    const first = ctx.recordPlayback(ack, [op], {
      producerId: 'playback_ack_slot',
      source: 'ordinary',
    });
    const second = ctx.recordPlayback(ack, [op], {
      producerId: 'playback_ack_slot',
      source: 'ordinary',
    });
    expect(first).toBeTruthy();
    expect(second).toBeNull();
    expect(rowsOfKind(entry, 'playback_evidence')).toHaveLength(1);
    const idem = rowsOfKind(entry, 'playback_idempotent');
    expect(idem).toHaveLength(1);
    expect(idem[0]).toMatchObject({
      producer_id: 'playback_ack_slot',
      op_key: rowsOfKind(entry, 'playback_evidence')[0].op_key,
      ack_body_hash: rowsOfKind(entry, 'playback_evidence')[0].ack_body_hash,
    });
    // idempotent is benign — never invalidating
    expect(ctx.deliveryLedger.invalid).toBeNull();
  });

  test('pre-admission: a slot resolving to zero deliveries stays telemetry (no row, no latch), a later valid ACK succeeds', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    // no deliveries at all — zero matches
    const miss = ctx.resolvePlaybackFromSlot({
      slot: { field: 'measured_zs_ohm', circuit: 1 },
      ackBody: { ok: true },
      source: 'ordinary',
    });
    expect(miss).toBeNull();
    expect(subRecords(entry)).toHaveLength(0);
    expect(ctx.deliveryLedger.invalid).toBeNull();
    // now a delivery lands and a valid ACK resolves
    const op = {
      extractionTurnId: 't5',
      field: 'measured_zs_ohm',
      circuit: 1,
      boardId: null,
      ordinal: 0,
    };
    ctx.recordDelivery([op], { producerId: 'result_frame_confirmation', kind: 'confirmation' });
    const hit = ctx.resolvePlaybackFromSlot({
      slot: { field: 'measured_zs_ohm', circuit: 1 },
      ackBody: { ok: true, n: 2 },
      source: 'ordinary',
    });
    expect(hit).toBeTruthy();
    expect(rowsOfKind(entry, 'playback_evidence')).toHaveLength(1);
    expect(ctx.deliveryLedger.invalid).toBeNull();
  });

  test('an integrity rejection at the ledger layer appends the rejected audit row and latches', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    const op = { extractionTurnId: 't6', field: 'x', circuit: null, boardId: null, ordinal: 0 };
    // playback without ANY delivery_attempt — reaches the ledger directly
    const res = ctx.recordPlayback({ ok: true }, [op], {
      producerId: 'playback_ack_slot',
      source: 'ordinary',
    });
    expect(res).toBeNull();
    const rejected = rowsOfKind(entry, 'playback_rejected');
    expect(rejected).toHaveLength(1);
    expect(rejected[0]).toMatchObject({
      producer_id: 'playback_ack_slot',
      reason: 'playback_without_delivery_attempt',
    });
    expect(ctx.deliveryLedger.invalid?.reason).toBe('playback_without_delivery_attempt');
  });
});

describe('C5 — freeze-time canonical rows', () => {
  test('a healthy session appends NO freeze-time row and freezes revision-stable and eligible', () => {
    const entry = makeEntry();
    composeCtx(entry);
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_h',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(true);
    expect(frozen.counts.revision_instability).toBe(0);
    expect(frozen.evidence.sub_records.filter((r) => r.kind === 'freeze_invalid')).toHaveLength(0);
  });

  test('an unconsumed fast-TTS provisional folds into the delivery_invalid latch at freeze time', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.reserveFastTts({
      correlationId: 'corr_orphan',
      candidate: { field: 'measured_zs_ohm', circuit: 3, board_id: null, value: '0.4' },
    });
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_p',
      boundary: 'session_stopped',
    });
    expect(ctx.deliveryLedger.invalid?.reason).toBe('fast_provisional_unconsumed');
    const freezeRows = frozen.evidence.sub_records.filter((r) => r.kind === 'freeze_invalid');
    expect(freezeRows).toEqual([
      expect.objectContaining({
        condition: 'delivery_invalid',
        reason: 'fast_provisional_unconsumed',
      }),
    ]);
    // The latch's own `eligible` flag deliberately keeps its quiescence-only
    // meaning; the C5 ineligibility rides the freeze row into the PROJECTION
    // (fold HOLD/INVALID), where 00C consumes it.
    expect(frozen.eligible).toBe(true);
    expect(buildEvidenceProjectionV1(frozen.candidate).eligible_for_family_credit).toBe(false);
    // the rows sit INSIDE the latched snapshot with stable revisions
    expect(frozen.counts.revision_instability).toBe(0);
    const latchedSnapshot = frozen.candidate; // observer.buildCandidate identity
    expect(latchedSnapshot.sub_records).toBe(frozen.evidence.sub_records);
  });

  test('a prepared-but-uncommitted dialogue delivery appends the outstanding-count freeze row', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    const payload = { question: 'Zs for circuit 4 is 0.4.' };
    ctx.deliveryEmit.prepare(payload, { operations: [] });
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_d',
      boundary: 'session_stopped',
    });
    const freezeRows = frozen.evidence.sub_records.filter((r) => r.kind === 'freeze_invalid');
    expect(freezeRows).toEqual([
      expect.objectContaining({ condition: 'delivery_prepared_outstanding', count: 1 }),
    ]);
    // quiescence-only latch flag; ineligibility rides the row into the fold
    expect(buildEvidenceProjectionV1(frozen.candidate).eligible_for_family_credit).toBe(false);
  });

  test('mutation and producer invalid latches surface as freeze-time rows', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.mutationObserver.markInvalid('turn_scope_reentered', {});
    getLifecycleLedger(entry).producerInvalid = Object.freeze({
      reason: 'producer_double_completion',
      detail: null,
    });
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_m',
      boundary: 'session_stopped',
    });
    const conditions = frozen.evidence.sub_records
      .filter((r) => r.kind === 'freeze_invalid')
      .map((r) => r.condition)
      .sort();
    expect(conditions).toEqual(['mutation_invalid', 'producer_invalid']);
    // quiescence-only latch flag; ineligibility rides the rows into the fold
    expect(buildEvidenceProjectionV1(frozen.candidate).eligible_for_family_credit).toBe(false);
  });
});

describe('C5 — api_transport in round_usage', () => {
  test('attributeRoundUsage carries the adapter-stamped API transport', () => {
    const row = attributeRoundUsage({
      provider: 'openai',
      requestedModel: 'gpt-5.6-luna',
      requestedTier: 'fast',
      responseModel: 'gpt-5.6-luna',
      responseTier: 'fast',
      usage: { input_tokens: 10, output_tokens: 5 },
      roundIdx: 0,
      apiTransport: 'responses',
    });
    expect(row.api_transport).toBe('responses');
    const anthropicRow = attributeRoundUsage({
      provider: 'anthropic',
      requestedModel: 'claude-haiku-4-5-20251001',
      responseModel: 'claude-haiku-4-5-20251001',
      usage: { input_tokens: 10, output_tokens: 5 },
      roundIdx: 0,
      apiTransport: 'anthropic_messages',
    });
    expect(anthropicRow.api_transport).toBe('anthropic_messages');
    // callers that thread nothing attribute null, never a guess
    const bare = attributeRoundUsage({
      provider: 'openai',
      requestedModel: 'gpt-5.6-luna',
      responseModel: 'gpt-5.6-luna',
      usage: {},
      roundIdx: 1,
    });
    expect(bare.api_transport).toBeNull();
  });

  test('the round_usage sub-record retains api_transport through the allowlist', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry);
    ctx.roundUsageSink(
      {
        provider: 'openai',
        api_transport: 'responses',
        requested_model: 'gpt-5.6-luna',
        requested_tier: 'fast',
        response_model: 'gpt-5.6-luna',
        response_tier: 'fast',
        billing_model: 'gpt-5.6-luna',
        billing_tier: 'fast',
        model_provenance: 'returned',
        tier_provenance: 'returned',
        attribution_status: 'attributed',
        reasoning_effort: 'none',
        prompt_cache_mode: 'explicit',
        prompt_cache_breakpoint_enabled: true,
        prompt_cache_key_id: 'pck',
        fresh_input_tokens: 1,
        cache_read_input_tokens: 2,
        cache_write_input_tokens: 3,
        output_tokens: 4,
        round_idx: 0,
      },
      { loopInvocationId: 'loop_x', billableKind: 'inspector_extraction' }
    );
    const rows = rowsOfKind(entry, 'round_usage');
    expect(rows).toHaveLength(1);
    expect(rows[0].api_transport).toBe('responses');
    expect(rows[0].billable_kind).toBe('inspector_extraction');
    expect(rows[0].loop_invocation_id).toBe('loop_x');
  });
});

// ── 5. The three-way agreement invariant (CREATED by this plan) ────────────

describe('three-way agreement (C0)', () => {
  function composeRichSession() {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_rich' });
    // dispatcher answered
    ctx.recordAskProduced({
      producerId: 'dispatcher_ask',
      runtimeId: 'toolu_r1',
      liveAskKey: K('r1'),
    });
    ctx.recordAskEmitted({ runtimeId: 'toolu_r1' });
    ctx.recordAskResolved({
      runtimeId: 'toolu_r1',
      terminal: 'answered',
      detail: { answer_frame_id: 'toolu_r1', transcript_resolved: true },
    });
    // dialogue answered + a rejected attempt first (stays visible, uncreditable)
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_r1',
      liveAskKey: K('r2'),
    });
    ctx.recordAskEmitted({ runtimeId: 'srv_r1' });
    ctx.recordAskResolved({
      runtimeId: 'srv_r1',
      terminal: 'answered',
      detail: { answer_frame_id: 'srv_r1', transcript_resolved: false },
    });
    ctx.recordAskResolved({
      runtimeId: 'srv_r1',
      terminal: 'answered',
      detail: { answer_frame_id: 'srv_r1', transcript_resolved: true },
    });
    // address-mirror answered + reissue
    ctx.recordAskProduced({
      producerId: 'address_mirror_ask',
      runtimeId: 'q_r1',
      liveAskKey: K('r3'),
    });
    ctx.recordAskEmitted({ runtimeId: 'q_r1' });
    ctx.recordAskEmitted({ runtimeId: 'q_r1' }); // same-id re-send → reissued_attempt
    ctx.recordAskResolved({
      runtimeId: 'q_r1',
      terminal: 'answered',
      detail: { answer_frame_id: 'q_r1', transcript_resolved: true },
    });
    // deliveries in every family + playbacks
    const op1 = {
      extractionTurnId: 'tA',
      field: 'measured_zs_ohm',
      circuit: 4,
      boardId: null,
      ordinal: 0,
    };
    const op2 = {
      extractionTurnId: 'tB',
      field: 'r1_r2_ohm',
      circuit: 7,
      boardId: null,
      ordinal: 0,
    };
    const op3 = {
      extractionTurnId: 'tC',
      field: 'client_address',
      circuit: null,
      boardId: null,
      ordinal: 0,
    };
    ctx.recordDelivery([op1], {
      producerId: 'result_frame_confirmation',
      kind: 'confirmation',
      wireTurnId: 'tA',
    });
    ctx.recordDelivery([op2], {
      producerId: 'dialogue_confirmation',
      kind: 'dialogue_confirmation',
    });
    ctx.recordDelivery([op3], {
      producerId: 'address_mirror_terminal',
      kind: 'address_mirror_terminal',
      claimLineage: 'result:tok_r',
    });
    ctx.recordPlayback({ ok: 1 }, [op1], { producerId: 'playback_ack_slot', source: 'ordinary' });
    ctx.recordPlayback({ ok: 2 }, [op3], {
      producerId: 'address_mirror_delivery_ack',
      source: 'address_mirror_delivery_ack',
    });
    // round usage (sub-records only — excluded from the comparable subset)
    ctx.roundUsageSink(
      { provider: 'openai', api_transport: 'responses', round_idx: 0 },
      { loopInvocationId: 'loop_r', billableKind: 'inspector_extraction' }
    );
    return entry;
  }

  test('latched-snapshot reconstruction and frozen-ledger projection agree (eligible session)', () => {
    const entry = composeRichSession();
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_rich',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(true);
    const fromSnapshot = buildEvidenceProjectionV1(frozen.candidate);
    const fromLedgers = projectFrozenLedgersV1(frozen);
    expect(comparableSubset(fromSnapshot)).toEqual(comparableSubset(fromLedgers));
    // and the rejected attempt is visible on the sub-records side only
    expect(fromSnapshot.ask_families.dialogue_script.rejected).toHaveLength(1);
    expect(fromSnapshot.family_gates.dialogue_script.ask_lifecycle_complete).toBe(true);
    expect(fromSnapshot.family_gates.address_mirror.playback_ack_proof).toBe(true);
  });

  test('agreement holds for an ineligible session (open ask + invalid latch)', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_bad' });
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_open',
      liveAskKey: K('b1'),
    });
    ctx.recordAskEmitted({ runtimeId: 'srv_open' });
    ctx.reserveFastTts({
      correlationId: 'corr_b',
      candidate: { field: 'x', circuit: null, board_id: null, value: '1' },
    });
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_bad',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(false);
    const fromSnapshot = buildEvidenceProjectionV1(frozen.candidate);
    const fromLedgers = projectFrozenLedgersV1(frozen);
    expect(comparableSubset(fromSnapshot)).toEqual(comparableSubset(fromLedgers));
    expect(fromSnapshot.eligible_for_family_credit).toBe(false);
    expect(fromSnapshot.ineligible_conditions).toEqual([
      { condition: 'delivery_invalid', reason: 'fast_provisional_unconsumed', count: null },
    ]);
  });

  test('the retained object-identity immutability check still holds beside the new invariant', () => {
    const entry = composeRichSession();
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_rich2',
      boundary: 'session_stopped',
    });
    expect(frozen.evidence.sub_records).toBe(frozen.candidate.sub_records);
    expect(Object.isFrozen(frozen.evidence.sub_records)).toBe(true);
  });
});

// ── 5b. The windowed-judge quiescence carve-out (C2) ───────────────────────

describe('windowed-judge carve-out — open-Tier-2-ask-ONLY non-quiescence (C2)', () => {
  test('an open dialogue_script ask at stop no longer holds the WINDOWED judge (00C counts stay strict)', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_jw' });
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_jw',
      liveAskKey: K('jw'),
    });
    ctx.recordAskEmitted({ runtimeId: 'srv_jw' });
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_jw',
      boundary: 'session_stopped',
    });
    // the FREEZE stays strict: ineligible, counts carry the open ask — this
    // is exactly what 00C's completion fold consumes
    expect(frozen.eligible).toBe(false);
    expect(frozen.counts.open_asks_dialogue_script).toBe(1);
    expect(frozen.counts.non_quiescent_at_stop).toBe(1);
    // the carve-out is OPT-IN (Codex r1 B-2/C-4): with no declared window
    // the judge is STRICT; only a caller declaring dialogue_script as
    // window-external proceeds (a stable open ask mutates nothing, and
    // dialogue asks are outside the corpus observation boundary).
    expect(composeCaptureInvalid(frozen)).toEqual({ reason: 'non_quiescent_at_stop' });
    expect(
      composeCaptureInvalid(frozen, { windowedOpenAskFamilies: ['dialogue_script'] })
    ).toBeNull();
  });

  test('an open DISPATCHER ask never passes the carve-out, even with a declared window', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_jw3' });
    ctx.recordAskProduced({
      producerId: 'dispatcher_ask',
      runtimeId: 'toolu_jw3',
      liveAskKey: K('jw3'),
    });
    ctx.recordAskEmitted({ runtimeId: 'toolu_jw3' });
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_jw3',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(false);
    // dispatcher asks are window-OBSERVABLE — the carve-out never covers them
    expect(composeCaptureInvalid(frozen, { windowedOpenAskFamilies: ['dialogue_script'] })).toEqual(
      { reason: 'non_quiescent_at_stop' }
    );
  });

  test('any OTHER non-quiescence beside the open ask still holds the judge', () => {
    const entry = makeEntry();
    entry.isExtracting = true; // an in-flight extraction CAN still mutate evidence
    const ctx = composeCtx(entry, { sessionId: 'sess_jw2' });
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_jw2',
      liveAskKey: K('jw2'),
    });
    ctx.recordAskEmitted({ runtimeId: 'srv_jw2' });
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_jw2',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(false);
    expect(composeCaptureInvalid(frozen, { windowedOpenAskFamilies: ['dialogue_script'] })).toEqual(
      { reason: 'non_quiescent_at_stop' }
    );
  });
});

// ── 5c. Codex r1 fix wave — regression pins ────────────────────────────────

describe('Codex r1 pins — quiescence hardening', () => {
  test('unknown_terminal never quietly closes an ask (counts non-quiescent)', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_ut' });
    ctx.recordAskProduced({
      producerId: 'dispatcher_ask',
      runtimeId: 'toolu_ut',
      liveAskKey: K('ut'),
    });
    ctx.recordAskEmitted({ runtimeId: 'toolu_ut' });
    ctx.recordAskResolved({ runtimeId: 'toolu_ut', terminal: 'unknown_terminal', detail: {} });
    expect(readInFlightCounts(entry).open_asks_dispatcher).toBe(1);
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_ut',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(false);
  });

  test('an ask open at the stop boundary stays counted even if it resolves answered during teardown awaits', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_race' });
    ctx.recordAskProduced({
      producerId: 'dialogue_script_ask',
      runtimeId: 'srv_race',
      liveAskKey: K('race'),
    });
    ctx.recordAskEmitted({ runtimeId: 'srv_race' });
    // teardown begins — the latch fires synchronously
    ctx.latchStopBoundary();
    // the answer lands DURING the teardown's awaited flushes
    ctx.recordAskResolved({
      runtimeId: 'srv_race',
      terminal: 'answered',
      detail: { answer_frame_id: 'srv_race', transcript_resolved: true },
    });
    expect(ctx.askLedger.entries[0].state).toBe('answered');
    // …but it was OPEN at the stop boundary, so it still counts
    expect(readInFlightCounts(entry).open_asks_dialogue_script).toBe(1);
    const frozen = freezeEvidenceCompletion(entry, {
      sessionId: 'sess_race',
      boundary: 'session_stopped',
    });
    expect(frozen.eligible).toBe(false);
  });

  test('the reconstruction and the counts must AGREE (count contradiction => ineligible)', () => {
    const snap = {
      sessionId: 'sess_contra',
      boundary: 'session_stopped',
      counts: {
        open_asks_dispatcher: 0,
        open_asks_dialogue_script: 0,
        open_asks_address_mirror: 0,
        non_quiescent_at_stop: 0,
        revision_instability: 0,
      },
      revisions: { usage_revision: 0 },
      sub_records: [
        {
          kind: 'ask_lifecycle',
          revision: 1,
          family: 'dialogue_script',
          stage: 'produced',
          runtime_id: 'x',
          live_ask_key: 'k',
        },
        {
          kind: 'ask_lifecycle',
          revision: 2,
          family: 'dialogue_script',
          stage: 'emitted',
          runtime_id: 'x',
        },
      ],
    };
    const proj = buildEvidenceProjectionV1(snap);
    expect(proj.count_contradictions).toEqual([
      { family: 'dialogue_script', counted: 0, derived: 1 },
    ]);
    expect(proj.eligible_for_family_credit).toBe(false);
  });
});

describe('Codex r1 pins — fast-TTS ACK lifecycle', () => {
  function promoteScenario() {
    const entry = makeEntry();
    const sessionId = 'sess_fp';
    const mo = createMutationObserver({ sessionId });
    const ctx = normaliseEvaluationContext(
      {
        observer: { buildCandidate: (snap) => snap, publish: () => {} },
        mutationObserver: mo,
        askLedger: createAskLedger(),
        deliveryLedger: createDeliveryLedger(),
      },
      { sessionId }
    );
    attachEvaluationContext(entry, ctx);
    mo.enterTurnScope('utt-fp');
    mo.bindFastCorrelation('corr_fp');
    mo.setOriginFrame({ origin: 'model_direct' });
    mo.commit({
      kind: 'reading',
      field: 'measured_zs_ohm',
      circuit: 4,
      board_id: null,
      value: '0.63',
    });
    mo.clearOriginFrame();
    mo.exitTurnScope();
    ctx.reserveFastTts({
      correlationId: 'corr_fp',
      candidate: { field: 'measured_zs_ohm', circuit: 4, board_id: null, value: '0.63' },
    });
    return { entry, ctx };
  }

  test('an ACK arriving AFTER promotion resolves immediately (the common ordering is never lost)', () => {
    const { entry, ctx } = promoteScenario();
    ctx.finishFastTts('corr_fp'); // receipt already exists -> promotes now
    expect(ctx.fastTtsReservations.get('corr_fp').promoted).toBe(true);
    ctx.stageFastPlaybackAck({ correlationId: 'corr_fp', ackBody: { ok: true, late: 1 } });
    const rows = rowsOfKind(entry, 'playback_evidence').filter(
      (r) => r.semantic_family === 'fast_tts'
    );
    expect(rows).toHaveLength(1);
    expect(ctx.deliveryLedger.playbacks).toHaveLength(1);
    expect(ctx.deliveryLedger.invalid).toBeNull();
  });

  test('byte-identical staged retransmissions keep their idempotent audit rows THROUGH promotion', () => {
    const { entry, ctx } = promoteScenario();
    const ack = { ok: true, n: 9 };
    ctx.stageFastPlaybackAck({ correlationId: 'corr_fp', ackBody: ack });
    ctx.stageFastPlaybackAck({ correlationId: 'corr_fp', ackBody: ack }); // byte-identical dup
    ctx.finishFastTts('corr_fp'); // promotion consumes both staged ACKs
    expect(
      rowsOfKind(entry, 'playback_evidence').filter((r) => r.semantic_family === 'fast_tts')
    ).toHaveLength(1);
    const idem = rowsOfKind(entry, 'playback_idempotent').filter(
      (r) => r.semantic_family === 'fast_tts'
    );
    expect(idem).toHaveLength(1);
    expect(ctx.deliveryLedger.invalid).toBeNull();
  });

  test('a wrong/stale fast correlation is PRE-ADMISSION telemetry: no row, no latch, later valid ACK succeeds', () => {
    const { entry, ctx } = promoteScenario();
    ctx.stageFastPlaybackAck({ correlationId: 'corr_STALE', ackBody: { ok: true } });
    expect(subRecords(entry).filter((r) => r.kind === 'playback_rejected')).toHaveLength(0);
    expect(ctx.deliveryLedger.invalid).toBeNull();
    ctx.finishFastTts('corr_fp');
    ctx.stageFastPlaybackAck({ correlationId: 'corr_fp', ackBody: { ok: true, v: 2 } });
    expect(ctx.deliveryLedger.playbacks).toHaveLength(1);
    expect(ctx.deliveryLedger.invalid).toBeNull();
  });
});

describe('Codex r1 pins — replacement lineage and mirror replays', () => {
  test('the successor produced row carries replaces_runtime_id (link-only replacements stay reconstructable)', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_rl' });
    ctx.recordAskProduced({
      producerId: 'dispatcher_ask',
      runtimeId: 'toolu_pred',
      liveAskKey: K('p1'),
    });
    ctx.recordAskEmitted({ runtimeId: 'toolu_pred' });
    ctx.recordAskResolved({ runtimeId: 'toolu_pred', terminal: 'timeout', detail: {} }); // already terminal
    ctx.recordAskProduced({
      producerId: 'dispatcher_ask',
      runtimeId: 'pvr-succ',
      liveAskKey: K('p2'),
      replacesRuntimeId: 'toolu_pred',
    });
    ctx.recordAskReplacement({
      predecessorRuntimeId: 'toolu_pred',
      successorRuntimeId: 'pvr-succ',
    });
    const produced = rowsOfKind(entry, 'ask_lifecycle').filter(
      (r) => r.stage === 'produced' && r.runtime_id === 'pvr-succ'
    );
    expect(produced).toHaveLength(1);
    expect(produced[0].replaces_runtime_id).toBe('toolu_pred');
    // link-only: the already-terminal predecessor gets NO transition row
    expect(rowsOfKind(entry, 'ask_lifecycle').filter((r) => r.stage === 'replaced')).toHaveLength(
      0
    );
    expect(rowsOfKind(entry, 'ask_transition_rejected')).toHaveLength(0);
  });

  test('a mirror REPLAY (new frame-binding attempt) appends its own delivery attempt; the dual frame does not', () => {
    const entry = makeEntry();
    const sessionId = 'sess_mr';
    const mo = createMutationObserver({ sessionId });
    const ctx = normaliseEvaluationContext(
      {
        observer: { buildCandidate: (snap) => snap, publish: () => {} },
        mutationObserver: mo,
        askLedger: createAskLedger(),
        deliveryLedger: createDeliveryLedger(),
      },
      { sessionId }
    );
    attachEvaluationContext(entry, ctx);
    const op = {
      extractionTurnId: 'tM',
      field: 'client_address',
      circuit: null,
      boardId: null,
      ordinal: 0,
    };
    // first send, extraction frame (attempt 1)
    ctx.recordAddressMirrorTerminal({
      claimLineage: 'result:tok_m',
      ops: [op],
      text: 'Address copied.',
      claimToken: 'clm_m',
      attempt: 1,
    });
    // same send, VCR frame (same attempt) — the dual-frame duplicate
    ctx.recordAddressMirrorTerminal({
      claimLineage: 'result:tok_m',
      ops: null,
      text: 'Address copied.',
      claimToken: 'clm_m',
      attempt: 1,
    });
    expect(rowsOfKind(entry, 'delivery_evidence')).toHaveLength(1);
    expect(rowsOfKind(entry, 'delivery_evidence')[0].delivery_claim_token).toBe('clm_m');
    // reconnect replay — a NEW attempt ordinal: one replay delivery attempt
    ctx.recordAddressMirrorTerminal({
      claimLineage: 'result:tok_m',
      ops: null,
      text: 'Address copied.',
      claimToken: 'clm_m',
      attempt: 2,
    });
    expect(rowsOfKind(entry, 'delivery_evidence')).toHaveLength(2);
    // the logical unit stays SINGULAR: one ACK still resolves one playback
    const row = ctx.recordAddressMirrorAck({
      claimLineage: 'result:tok_m',
      ackBody: { type: 'address_mirror_delivery_ack', kind: 'result', token: 'tok_m' },
    });
    expect(row).toBeTruthy();
    expect(ctx.deliveryLedger.playbacks).toHaveLength(1);
  });
});

describe('Codex r1 — the reusable ACK-sequence action fixture (shared with 00C Stage A)', () => {
  const OP = (o) => ({
    extractionTurnId: o.turn,
    field: o.field,
    circuit: o.circuit ?? null,
    boardId: null,
    ordinal: 0,
  });

  test.each(ackSequences.cases.map((c) => [c.name, c]))('%s', (_name, kase) => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: `sess_${_name}` });
    for (const act of kase.actions) {
      if (act.action === 'delivery') {
        ctx.recordDelivery([OP(act.op)], { producerId: act.producer_id, kind: act.kind });
      } else if (act.action === 'playback') {
        ctx.recordPlayback(act.ack_body, [OP(act.op)], {
          producerId: act.producer_id,
          source: act.source,
        });
      } else if (act.action === 'playback_slot' || act.action === 'playback_slot_miss') {
        ctx.resolvePlaybackFromSlot({ slot: act.slot, ackBody: act.ack_body, source: 'ordinary' });
      } else if (act.action === 'fast_ack') {
        ctx.stageFastPlaybackAck({ correlationId: act.correlation_id, ackBody: act.ack_body });
      } else {
        throw new Error(`unknown fixture action: ${act.action}`);
      }
    }
    expect(rowsOfKind(entry, 'playback_evidence')).toHaveLength(kase.expected.playback_evidence);
    expect(rowsOfKind(entry, 'playback_idempotent')).toHaveLength(
      kase.expected.playback_idempotent
    );
    expect(rowsOfKind(entry, 'playback_rejected')).toHaveLength(kase.expected.playback_rejected);
    expect(ctx.deliveryLedger.invalid).toEqual(kase.expected.delivery_invalid);
  });
});

describe('Codex r1 — executable rejection-regime table', () => {
  test('transition rejection: answered_without_full_proof — row, NO latch, entry stays open', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_rr1' });
    ctx.recordAskProduced({ producerId: 'dispatcher_ask', runtimeId: 'r1', liveAskKey: K('rr1') });
    ctx.recordAskEmitted({ runtimeId: 'r1' });
    ctx.recordAskResolved({
      runtimeId: 'r1',
      terminal: 'answered',
      detail: { answer_frame_id: 'WRONG', transcript_resolved: true },
    });
    expect(rowsOfKind(entry, 'ask_transition_rejected')).toHaveLength(1);
    expect(ctx.askLedger.invalid).toBeNull();
    expect(ctx.askLedger.open()).toHaveLength(1);
  });

  test.each([
    ['duplicate_runtime_binding'],
    ['resolution_without_emitted'],
    ['reissue_without_emitted'],
    ['replacement_predecessor_unknown'],
    ['emitted_without_binding'],
  ])('structural ask rejection %s — row AND latch', (reason) => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: `sess_${reason}` });
    if (reason === 'duplicate_runtime_binding') {
      ctx.recordAskProduced({ producerId: 'dispatcher_ask', runtimeId: 'd1', liveAskKey: K('a') });
      ctx.recordAskProduced({ producerId: 'dispatcher_ask', runtimeId: 'd1', liveAskKey: K('a') });
    } else if (reason === 'resolution_without_emitted') {
      ctx.recordAskResolved({ runtimeId: 'ghost', terminal: 'timeout', detail: {} });
    } else if (reason === 'reissue_without_emitted') {
      ctx.recordAskProduced({ producerId: 'dispatcher_ask', runtimeId: 'd2', liveAskKey: K('b') });
      ctx.recordAskEmitted({ runtimeId: 'd2' });
      ctx.recordAskResolved({ runtimeId: 'd2', terminal: 'timeout', detail: {} });
      ctx.recordAskEmitted({ runtimeId: 'd2' }); // re-send of a terminal entry
    } else if (reason === 'replacement_predecessor_unknown') {
      ctx.recordAskReplacement({ predecessorRuntimeId: 'nope', successorRuntimeId: 'succ' });
    } else if (reason === 'emitted_without_binding') {
      ctx.recordAskEmitted({ runtimeId: 'unbound' });
    }
    const rejected = rowsOfKind(entry, 'ask_transition_rejected');
    expect(rejected.length).toBeGreaterThanOrEqual(1);
    expect(rejected.some((r) => r.reason === reason)).toBe(true);
    expect(ctx.askLedger.invalid?.reason).toBe(reason);
  });

  test('unknown rejection reason fails loud as unknown_rejection_reason (closed vocabulary)', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_ur' });
    ctx.recordDeliveryRejected({ producerId: 'dialogue_confirmation', reason: 'made_up_reason' });
    const rows = rowsOfKind(entry, 'delivery_rejected');
    expect(rows).toHaveLength(1);
    expect(rows[0].reason).toBe('unknown_rejection_reason');
    expect(ctx.deliveryLedger.invalid?.reason).toBe('unknown_rejection_reason');
  });

  test('an unregistered producer on the rejected helper routes through producer_unknown', () => {
    const entry = makeEntry();
    const ctx = composeCtx(entry, { sessionId: 'sess_up' });
    ctx.recordDeliveryRejected({
      producerId: 'not_registered',
      reason: 'dialogue_delivery_binding_ambiguous',
    });
    expect(rowsOfKind(entry, 'delivery_rejected')).toHaveLength(0);
    expect(rowsOfKind(entry, 'producer_unknown')).toHaveLength(1);
  });
});

// ── 6. SEMANTIC_ORACLE_INPUTS direct membership ────────────────────────────

describe('SEMANTIC_ORACLE_INPUTS membership (C0)', () => {
  const REQUIRED = [
    'tests/fixtures/test-contracts/plan00-evidence-contract/schema-v1.json',
    'tests/fixtures/test-contracts/plan00-evidence-contract/snapshot-v1.json',
    'tests/fixtures/test-contracts/plan00-evidence-contract/projection-v1.json',
    'tests/fixtures/test-contracts/plan00-evidence-contract/snapshot-ineligible-v1.json',
    'tests/fixtures/test-contracts/plan00-evidence-contract/projection-ineligible-v1.json',
    'tests/fixtures/test-contracts/plan00-evidence-contract/ack-sequences-v1.json',
    'src/extraction/plan00-evidence-registry.js',
    'src/extraction/plan00-evidence-projection.js',
  ];

  test.each(REQUIRED)('%s is an enumerated semantic-oracle input', (rel) => {
    expect(SEMANTIC_ORACLE_INPUTS).toContain(rel);
  });

  test('the future 00C consumer is EXPLICITLY excluded (00C digest-partition rule)', () => {
    expect(SEMANTIC_ORACLE_INPUTS).not.toContain('src/extraction/plan00-session-manifest.js');
  });
});
