/**
 * Plan A1a (2026-07-27, feedback id 101) — tests 1 & 2:
 * CLEAR_BOARD_READING_FIELD_ENUM + BOARD_CLEAR_EXCLUSIONS pins.
 *
 * Fail-closed contract: PRODUCTION derives the enum at module load
 * (BOARD_FIELD_ENUM minus BOARD_CLEAR_EXCLUSIONS); ONLY this test owns the
 * pasted 78-member literal. A new field_schema.json key grows the derived
 * enum, the literal below does not, and the suite reddens until a human
 * classifies the new key (structural exclusion vs clearable candidate).
 * Pasting a literal on BOTH sides would let a new schema key pass unnoticed.
 *
 * RED mechanism on unfixed main: the exports do not exist (undefined).
 */

const { BOARD_FIELD_ENUM, BOARD_CLEAR_EXCLUSIONS, CLEAR_BOARD_READING_FIELD_ENUM, TOOL_SCHEMAS } =
  await import('../extraction/stage6-tool-schemas.js');
const { FIELD_CORRECTIONS } = await import('../extraction/field-name-corrections.js');
const { CLEAR_WIRE_EXEMPT } = await import('../extraction/stage6-event-bundler.js');

// Test 1's committed literal — GENERATED by executing the real builder
// (filter _ui_* → Set-dedupe → sort → subtract the six exclusions), never
// hand-assembled from section counts (the raw 49+15+21=85 double-counts the
// one cross-section key; the real union is 84).
const EXPECTED_CLEAR_ENUM = [
  'address',
  'agreed_limitations',
  'agreed_with',
  'bonding_conductor_continuity',
  'bonding_conductor_csa',
  'bonding_conductor_material',
  'bonding_gas',
  'bonding_lightning',
  'bonding_oil',
  'bonding_other',
  'bonding_other_na',
  'bonding_structural_steel',
  'bonding_water',
  'client_address',
  'client_county',
  'client_name',
  'client_postcode',
  'client_town',
  'comments',
  'county',
  'date_of_inspection',
  'date_of_previous_inspection',
  'earth_electrode_location',
  'earth_electrode_resistance',
  'earth_electrode_type',
  'earthing_arrangement',
  'earthing_conductor_continuity',
  'earthing_conductor_csa',
  'earthing_conductor_material',
  'evidence_of_additions_alterations',
  'extent',
  'general_condition',
  'installation_records_available',
  'ipf_at_db',
  'live_conductors',
  'location',
  'main_switch_bs_en',
  'main_switch_conductor_csa',
  'main_switch_conductor_material',
  'main_switch_current',
  'main_switch_fuse_setting',
  'main_switch_location',
  'main_switch_poles',
  'main_switch_voltage',
  'manufacturer',
  'means_earthing_distributor',
  'means_earthing_electrode',
  'next_inspection_years',
  'nominal_frequency',
  'nominal_voltage_u',
  'nominal_voltage_uo',
  'number_of_supplies',
  'operational_limitations',
  'phases',
  'postcode',
  'premises_description',
  'prospective_fault_current',
  'rcd_operating_current',
  'rcd_operating_current_test',
  'rcd_operating_time',
  'rcd_operating_time_test',
  'rcd_time_delay',
  'rcd_time_delay_test',
  'spd_bs_en',
  'spd_rated_current',
  'spd_short_circuit',
  'spd_type_supply',
  'sub_main_cable_csa',
  'sub_main_cable_material',
  'sub_main_cpc_csa',
  'supply_polarity_confirmed',
  'surge_spd_bs_en',
  'surge_spd_present',
  'surge_spd_type',
  'surge_status_indicator',
  'town',
  'ze',
  'ze_at_db',
];

describe('CLEAR_BOARD_READING_FIELD_ENUM (plan A1a test 1)', () => {
  test('equals the committed 78-member literal (fail-closed against new schema keys)', () => {
    expect(CLEAR_BOARD_READING_FIELD_ENUM).toEqual(EXPECTED_CLEAR_ENUM);
    // Derive the count from the array — never a second hand-typed number.
    expect(CLEAR_BOARD_READING_FIELD_ENUM).toHaveLength(EXPECTED_CLEAR_ENUM.length);
    expect(EXPECTED_CLEAR_ENUM).toHaveLength(78);
  });

  test('production derives the enum from BOARD_FIELD_ENUM minus the exclusions', () => {
    // The derived-production property: recomputing the subtraction from the
    // live BOARD_FIELD_ENUM must reproduce the export exactly, so the export
    // can never be a stale pasted literal.
    const derived = BOARD_FIELD_ENUM.filter((k) => !BOARD_CLEAR_EXCLUSIONS.has(k));
    expect(CLEAR_BOARD_READING_FIELD_ENUM).toEqual(derived);
  });

  test('the advertised tool schema carries exactly this enum, appended last (index 18)', () => {
    const tool = TOOL_SCHEMAS[18];
    expect(tool.name).toBe('clear_board_reading');
    expect(tool.input_schema.properties.field.enum).toEqual(CLEAR_BOARD_READING_FIELD_ENUM);
    expect(tool.input_schema.required).toEqual(['field', 'reason']);
    // Deliberately NO board_id param — multi-board targeting is
    // select_board-then-clear, the same two-step as record_board_reading.
    expect(tool.input_schema.properties.board_id).toBeUndefined();
    expect(tool.input_schema.properties.circuit).toBeUndefined();
  });
});

describe('BOARD_CLEAR_EXCLUSIONS (plan A1a test 2)', () => {
  test('leg (a): exactly six members — five structural + the ze wire-alias de-dupe', () => {
    expect([...BOARD_CLEAR_EXCLUSIONS].sort()).toEqual(
      [
        'name',
        'board_type',
        'parent_board_id',
        'feed_circuit_ref',
        'sort_order',
        'earth_loop_impedance_ze',
      ].sort()
    );
    // All six are genuine BOARD_FIELD_ENUM members (an exclusion of a
    // non-member would be dead weight masking a rename)…
    for (const excluded of BOARD_CLEAR_EXCLUSIONS) {
      expect(BOARD_FIELD_ENUM).toContain(excluded);
    }
    // …and none survives into the clear enum.
    for (const excluded of BOARD_CLEAR_EXCLUSIONS) {
      expect(CLEAR_BOARD_READING_FIELD_ENUM).not.toContain(excluded);
    }
  });

  test('leg (b): COMPUTED — no enum member is rewritten by FIELD_CORRECTIONS onto another member (wire names pairwise distinct)', () => {
    // A literal-only pin cannot know a future FIELD_CORRECTIONS entry
    // collapsed two members onto one wire name (the `ze` collision class:
    // ze and earth_loop_impedance_ze both wired out as 'ze' until the
    // sixth exclusion removed the alias). Honour CLEAR_WIRE_EXEMPT exactly
    // as the bundler does.
    const wireNames = CLEAR_BOARD_READING_FIELD_ENUM.map((f) =>
      CLEAR_WIRE_EXEMPT.has(f) ? f : (FIELD_CORRECTIONS[f] ?? f)
    );
    const seen = new Map();
    for (let i = 0; i < wireNames.length; i += 1) {
      const wire = wireNames[i];
      if (seen.has(wire)) {
        throw new Error(
          `Wire-name collision: enum members '${seen.get(wire)}' and ` +
            `'${CLEAR_BOARD_READING_FIELD_ENUM[i]}' both canonicalise to '${wire}' — ` +
            `add a wire-alias exclusion to BOARD_CLEAR_EXCLUSIONS`
        );
      }
      seen.set(wire, CLEAR_BOARD_READING_FIELD_ENUM[i]);
    }
    expect(new Set(wireNames).size).toBe(wireNames.length);
  });

  test('the two reachable FIELD_CORRECTIONS rewrites are pinned: pfc rewrite live, ze rewrite excluded', () => {
    // prospective_fault_current -> 'pfc' is the ONE rewrite reachable from a
    // board clear (the wire name is NOT an enum member; both clients route
    // it). earth_loop_impedance_ze -> 'ze' is unreachable because the alias
    // is excluded from the enum.
    expect(FIELD_CORRECTIONS.prospective_fault_current).toBe('pfc');
    expect(CLEAR_BOARD_READING_FIELD_ENUM).toContain('prospective_fault_current');
    expect(CLEAR_BOARD_READING_FIELD_ENUM).not.toContain('pfc');
    expect(FIELD_CORRECTIONS.earth_loop_impedance_ze).toBe('ze');
    expect(CLEAR_BOARD_READING_FIELD_ENUM).toContain('ze');
  });
});
