/**
 * Stage 6 Phase 2 Plan 02-04 — Observation dispatcher tests.
 *
 * WHAT: Behavioural tests for dispatchRecordObservation + dispatchDeleteObservation
 * covering happy-path mutation, cross-receiver consistency (BLOCK-1), noop-on-absent
 * delete (BLOCK-2), PII-free logging, per-turn-writes isolation, and envelope shape.
 *
 * WHY these tests drive the real implementation (TDD RED then GREEN):
 *  - Group 1 proves the dispatcher calls appendObservation and surfaces the id.
 *  - Group 3-4 proves delete handles both the happy-found path and the absence
 *    noop path (is_error:false — the §Q8 research pin).
 *  - Group 5 locks the PII guard so no inspector free-text (client name,
 *    address fragments) can leak into log rows.
 *  - Group 6 exercises the per-turn reset vs cross-turn session persistence
 *    invariant (Pitfall #2 mitigation from Plan 02-02).
 *  - Group 7 locks the full stage6_tool_call row shape.
 *
 * NOTE on cross-receiver consistency (BLOCK-1):
 *  Per Plan 02-01 SUMMARY, the appendObservation atom only mutates
 *  session.extractedObservations. session.stateSnapshot.observations is a
 *  separate legacy-path structure (text-lowercase-equality dedup surface) that
 *  is NOT touched by the atom. The cross-receiver consistency assertion we CAN
 *  make is: envelope.observation_id === session.extractedObservations[n].id.
 *  That is the only authoritative id surface in the tool-call path.
 */

import { jest } from '@jest/globals';
import { WRITE_DISPATCHERS } from '../extraction/stage6-dispatchers.js';
import { createPerTurnWrites } from '../extraction/stage6-per-turn-writes.js';

function makeSession() {
  return {
    sessionId: 'sess-test',
    stateSnapshot: { circuits: {}, pending_readings: [], observations: [], validation_alerts: [] },
    extractedObservations: [],
  };
}

function makeLogger() {
  const calls = [];
  return {
    info: jest.fn((event, row) => calls.push({ event, row })),
    warn: jest.fn(),
    error: jest.fn(),
    calls,
  };
}

function makeCtx({ session, logger, perTurnWrites }) {
  return {
    session,
    logger,
    turnId: 'sess-test-turn-1',
    perTurnWrites,
    round: 1,
  };
}

// Shape: matches UUIDv4 (as generated by node:crypto.randomUUID() in the mutator atom)
const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

describe('dispatchRecordObservation', () => {
  test('happy path: minimal observation → envelope ok:true + observation_id, session array grows', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();
    const call = {
      tool_call_id: 'tu_obs_1',
      name: 'record_observation',
      input: { text: 'RCD type AC present', code: 'C3' },
    };

    const result = await WRITE_DISPATCHERS.record_observation(
      call,
      makeCtx({ session, logger, perTurnWrites })
    );

    expect(result.tool_use_id).toBe('tu_obs_1');
    expect(result.is_error).toBe(false);
    const body = JSON.parse(result.content);
    expect(body.ok).toBe(true);
    expect(body.observation_id).toMatch(UUID_V4_REGEX);

    // session.extractedObservations grew by one, id matches envelope.
    expect(session.extractedObservations.length).toBe(1);
    expect(session.extractedObservations[0].id).toBe(body.observation_id);
    expect(session.extractedObservations[0].text).toBe('RCD type AC present');
    expect(session.extractedObservations[0].code).toBe('C3');

    // perTurnWrites captured the write.
    expect(perTurnWrites.observations.length).toBe(1);
    expect(perTurnWrites.observations[0].id).toBe(body.observation_id);

    // Log row: outcome 'ok', input_summary contains id+code only.
    expect(logger.info).toHaveBeenCalledTimes(1);
    const row = logger.info.mock.calls[0][1];
    expect(row.outcome).toBe('ok');
    expect(row.is_error).toBe(false);
    expect(row.input_summary).toEqual({ observation_id: body.observation_id, code: 'C3' });
  });

  test('BLOCK-1 regression guard: id returned in envelope === session.extractedObservations[0].id', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();

    const result = await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_obs_2',
        name: 'record_observation',
        input: { text: 'Ze too high', code: 'C2' },
      },
      makeCtx({ session, logger, perTurnWrites })
    );

    const envelopeId = JSON.parse(result.content).observation_id;
    expect(envelopeId).toBe(session.extractedObservations[0].id);
    expect(envelopeId).toBe(perTurnWrites.observations[0].id);
  });

  test('full-field observation: code C2 + location + suggested_regulation persisted, PII absent from log', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();
    const call = {
      tool_call_id: 'tu_obs_3',
      name: 'record_observation',
      input: {
        text: 'Main earth bond not visible',
        code: 'C2',
        location: 'hall cupboard',
        circuit: 1,
        suggested_regulation: '411.3.1.1',
      },
    };

    const result = await WRITE_DISPATCHERS.record_observation(
      call,
      makeCtx({ session, logger, perTurnWrites })
    );

    expect(result.is_error).toBe(false);
    const stored = session.extractedObservations[0];
    expect(stored.code).toBe('C2');
    expect(stored.location).toBe('hall cupboard');
    expect(stored.circuit).toBe(1);
    expect(stored.suggested_regulation).toBe('411.3.1.1');
    expect(stored.text).toBe('Main earth bond not visible');

    // Log row MUST contain only {observation_id, code} — not location / text / suggested_regulation.
    const row = logger.info.mock.calls[0][1];
    expect(Object.keys(row.input_summary).sort()).toEqual(['code', 'observation_id']);
    expect(row.input_summary.code).toBe('C2');
  });

  test('schedule_item persists through dispatcher to session + perTurnWrites (BPG4 restoration 2026-05-01)', async () => {
    // The Schedule of Inspection section number flows through the same path
    // as suggested_regulation. iOS's ObservationScheduleLinker reads it
    // off the observation row to auto-tick the matching schedule line.
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();
    const result = await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_obs_sched',
        name: 'record_observation',
        input: {
          text: 'No RCD on outdoor sockets',
          code: 'C2',
          location: 'rear garden',
          circuit: 6,
          suggested_regulation: '411.3.3',
          schedule_item: '5.12.1',
        },
      },
      makeCtx({ session, logger, perTurnWrites })
    );
    expect(result.is_error).toBe(false);
    expect(session.extractedObservations[0].schedule_item).toBe('5.12.1');
    expect(perTurnWrites.observations[0].schedule_item).toBe('5.12.1');
    // PII guard remains: schedule_item is allowed in the perTurnWrites shape
    // (iOS consumer) but MUST NOT appear in the structured log row.
    const row = logger.info.mock.calls[0][1];
    expect(Object.keys(row.input_summary).sort()).toEqual(['code', 'observation_id']);
  });

  test('schedule_item null/undefined → stored as null (no section applies)', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();
    await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_obs_no_sched',
        name: 'record_observation',
        input: {
          text: 'General installation note',
          code: 'C3',
          // schedule_item omitted entirely
        },
      },
      makeCtx({ session, logger, perTurnWrites })
    );
    expect(session.extractedObservations[0].schedule_item).toBeNull();
    expect(perTurnWrites.observations[0].schedule_item).toBeNull();
  });
});

describe('dispatchDeleteObservation', () => {
  test('happy path: delete existing id → envelope ok:true, session array shrinks, perTurnWrites tracks', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();

    // Seed: record first, then delete.
    const recordResult = await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_rec_1',
        name: 'record_observation',
        input: { text: 'Socket damage', code: 'C2' },
      },
      makeCtx({ session, logger, perTurnWrites })
    );
    const id = JSON.parse(recordResult.content).observation_id;
    expect(session.extractedObservations.length).toBe(1);

    const delResult = await WRITE_DISPATCHERS.delete_observation(
      {
        tool_call_id: 'tu_del_1',
        name: 'delete_observation',
        input: { observation_id: id, reason: 'misheard' },
      },
      makeCtx({ session, logger, perTurnWrites })
    );

    expect(delResult.tool_use_id).toBe('tu_del_1');
    expect(delResult.is_error).toBe(false);
    const body = JSON.parse(delResult.content);
    expect(body.ok).toBe(true);
    expect(body.noop).toBeUndefined();

    // Session shrank.
    expect(session.extractedObservations.length).toBe(0);

    // Per-turn delete log.
    expect(perTurnWrites.deletedObservations.length).toBe(1);
    expect(perTurnWrites.deletedObservations[0]).toEqual({ id, reason: 'misheard' });

    // Two log rows total (one per dispatch); the delete row has outcome 'ok'.
    expect(logger.info).toHaveBeenCalledTimes(2);
    const delRow = logger.info.mock.calls[1][1];
    expect(delRow.tool).toBe('delete_observation');
    expect(delRow.outcome).toBe('ok');
    expect(delRow.is_error).toBe(false);
    expect(delRow.input_summary).toEqual({ observation_id: id, reason: 'misheard' });
  });

  test('reason propagates to perTurnWrites.deletedObservations', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();

    const rec = await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_rec_2',
        name: 'record_observation',
        input: { text: 'Cable exposed', code: 'C1' },
      },
      makeCtx({ session, logger, perTurnWrites })
    );
    const id = JSON.parse(rec.content).observation_id;

    await WRITE_DISPATCHERS.delete_observation(
      {
        tool_call_id: 'tu_del_2',
        name: 'delete_observation',
        input: { observation_id: id, reason: 'superseded' },
      },
      makeCtx({ session, logger, perTurnWrites })
    );

    expect(perTurnWrites.deletedObservations[0].reason).toBe('superseded');
  });

  test('BLOCK-2: delete-already-deleted is noop (is_error:false), NOT error', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();

    // Shape-valid UUID that is NOT in session.extractedObservations.
    const absentId = '11111111-2222-4333-8444-555555555555';

    const result = await WRITE_DISPATCHERS.delete_observation(
      {
        tool_call_id: 'tu_del_absent',
        name: 'delete_observation',
        input: { observation_id: absentId, reason: 'misheard' },
      },
      makeCtx({ session, logger, perTurnWrites })
    );

    // Envelope: ok:true + noop:true + reason.
    expect(result.is_error).toBe(false);
    const body = JSON.parse(result.content);
    expect(body).toEqual({ ok: true, noop: true, reason: 'observation_not_found' });

    // Session UNCHANGED.
    expect(session.extractedObservations.length).toBe(0);
    // perTurnWrites UNCHANGED.
    expect(perTurnWrites.deletedObservations.length).toBe(0);

    // Log row: outcome 'noop', is_error false, validation_error null.
    const row = logger.info.mock.calls[0][1];
    expect(row.outcome).toBe('noop');
    expect(row.is_error).toBe(false);
    expect(row.validation_error).toBeNull();
    expect(row.input_summary).toEqual({ observation_id: absentId, reason: 'misheard' });
  });
});

describe('PII guard (Group 5)', () => {
  test('record_observation: no text/location/suggested_regulation leaks into logger JSON', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();

    await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_pii',
        name: 'record_observation',
        input: {
          text: 'client name Mr Smith, 42 Acacia Ave',
          code: 'C2',
          location: 'kitchen under sink',
          suggested_regulation: 'BS 7671 Table 41.1',
        },
      },
      makeCtx({ session, logger, perTurnWrites })
    );

    const serialised = JSON.stringify(logger.calls);
    expect(serialised).not.toContain('Mr Smith');
    expect(serialised).not.toContain('Acacia');
    expect(serialised).not.toContain('under sink');
    expect(serialised).not.toContain('Table 41.1');
  });
});

describe('Per-turn writes isolation across turns (Group 6 — BLOCK-1 cross-turn rule)', () => {
  test('two dispatches on different perTurnWrites instances: session persists; perTurnWrites does not', async () => {
    const session = makeSession();
    const logger = makeLogger();

    // Turn 1
    const turn1Writes = createPerTurnWrites();
    await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_t1',
        name: 'record_observation',
        input: { text: 'First observation', code: 'C3' },
      },
      { session, logger, turnId: 'sess-test-turn-1', perTurnWrites: turn1Writes, round: 1 }
    );

    // Turn 2 — fresh perTurnWrites.
    const turn2Writes = createPerTurnWrites();
    await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_t2',
        name: 'record_observation',
        input: { text: 'Second observation', code: 'C2' },
      },
      { session, logger, turnId: 'sess-test-turn-2', perTurnWrites: turn2Writes, round: 1 }
    );

    // Session sees BOTH (cross-turn persistence).
    expect(session.extractedObservations.length).toBe(2);
    expect(session.extractedObservations[0].text).toBe('First observation');
    expect(session.extractedObservations[1].text).toBe('Second observation');

    // perTurnWrites sees ONE each (reset-per-turn contract).
    expect(turn1Writes.observations.length).toBe(1);
    expect(turn2Writes.observations.length).toBe(1);
    expect(turn1Writes.observations[0].text).toBe('First observation');
    expect(turn2Writes.observations[0].text).toBe('Second observation');
  });
});

describe('Logger row shape (Group 7)', () => {
  test('record_observation log row has full canonical stage6_tool_call shape — no extras, no PII', async () => {
    const session = makeSession();
    const logger = makeLogger();
    const perTurnWrites = createPerTurnWrites();

    await WRITE_DISPATCHERS.record_observation(
      {
        tool_call_id: 'tu_shape',
        name: 'record_observation',
        input: { text: 'Fixture text should not appear in log', code: 'C3' },
      },
      makeCtx({ session, logger, perTurnWrites })
    );

    expect(logger.info).toHaveBeenCalledTimes(1);
    const [event, row] = logger.info.mock.calls[0];
    expect(event).toBe('stage6_tool_call');

    // Row shape: exactly these keys.
    expect(Object.keys(row).sort()).toEqual(
      [
        'input_summary',
        'is_error',
        'outcome',
        'phase',
        'round',
        'sessionId',
        'tool',
        'tool_use_id',
        'turnId',
        'validation_error',
      ].sort()
    );

    expect(row.sessionId).toBe('sess-test');
    expect(row.turnId).toBe('sess-test-turn-1');
    expect(row.tool_use_id).toBe('tu_shape');
    expect(row.tool).toBe('record_observation');
    expect(row.round).toBe(1);
    expect(row.phase).toBe(2);
    expect(row.is_error).toBe(false);
    expect(row.outcome).toBe('ok');
    expect(row.validation_error).toBeNull();

    // Fixture text never appears anywhere in the row.
    expect(JSON.stringify(row)).not.toContain('Fixture text should not appear in log');
  });
});

describe('Sanity: WRITE_DISPATCHERS exports (export regression guard)', () => {
  test('WRITE_DISPATCHERS has both observation dispatchers as async functions', () => {
    expect(typeof WRITE_DISPATCHERS.record_observation).toBe('function');
    expect(typeof WRITE_DISPATCHERS.delete_observation).toBe('function');
  });
});
