/**
 * WhatsApp Cloud API client for CertMate.
 * Uses Meta's WhatsApp Business Cloud API to send certificate PDFs to clients.
 *
 * Required env vars:
 *   WHATSAPP_TOKEN          - Meta API access token
 *   WHATSAPP_PHONE_NUMBER_ID - WhatsApp Business phone number ID
 */

import logger from "./logger.js";

const WHATSAPP_TOKEN = process.env.WHATSAPP_TOKEN;
const WHATSAPP_PHONE_NUMBER_ID = process.env.WHATSAPP_PHONE_NUMBER_ID;
const API_VERSION = "v18.0";
const BASE_URL = `https://graph.facebook.com/${API_VERSION}`;

/**
 * Check whether the WhatsApp integration is configured.
 * @returns {boolean}
 */
export function isConfigured() {
  return !!(process.env.WHATSAPP_TOKEN && process.env.WHATSAPP_PHONE_NUMBER_ID);
}

/**
 * Format a UK phone number to international E.164 format (+44...).
 *
 * Accepts:
 *   07700 900123   -> +447700900123
 *   +447700900123  -> +447700900123
 *   447700900123   -> +447700900123
 *   00447700900123 -> +447700900123
 *
 * @param {string} phone - Raw phone number input
 * @returns {string} E.164 formatted number
 * @throws {Error} if the number cannot be parsed as a UK mobile
 */
export function formatUKPhoneNumber(phone) {
  // Strip all whitespace, dashes, and parentheses
  let cleaned = phone.replace(/[\s\-()]/g, "");

  // Remove leading + for easier processing
  if (cleaned.startsWith("+")) {
    cleaned = cleaned.slice(1);
  }

  // Remove leading 00 (international dialling prefix)
  if (cleaned.startsWith("00")) {
    cleaned = cleaned.slice(2);
  }

  // UK number starting with 0 — replace leading 0 with 44
  if (cleaned.startsWith("0")) {
    cleaned = "44" + cleaned.slice(1);
  }

  // At this point it should start with 44
  if (!cleaned.startsWith("44")) {
    throw new Error("Not a valid UK phone number — must start with 07, +44, or 44");
  }

  // UK numbers (after country code) should be 10 digits, making 12 total
  if (cleaned.length !== 12) {
    throw new Error(
      `Invalid UK phone number length — expected 12 digits (44 + 10), got ${cleaned.length}`
    );
  }

  return "+" + cleaned;
}

/**
 * Validate that a phone string looks like a UK phone number.
 * @param {string} phone
 * @returns {{ valid: boolean, formatted?: string, error?: string }}
 */
export function validateUKPhone(phone) {
  try {
    const formatted = formatUKPhoneNumber(phone);
    return { valid: true, formatted };
  } catch (err) {
    return { valid: false, error: err.message };
  }
}

/**
 * Send a certificate document via WhatsApp.
 *
 * @param {Object} options
 * @param {string} options.to        - Recipient phone number (any UK format)
 * @param {string} options.address   - Property address for the caption
 * @param {string} options.mediaUrl  - Publicly accessible (presigned) URL to the PDF
 * @param {string} [options.certificateType="EICR"] - "EICR" or "EIC"
 * @returns {Promise<Object>} WhatsApp API response
 */
export async function sendCertificateViaWhatsApp({ to, address, mediaUrl, certificateType = "EICR" }) {
  if (!isConfigured()) {
    throw new Error("WhatsApp not configured — WHATSAPP_TOKEN and WHATSAPP_PHONE_NUMBER_ID required");
  }

  const formatted = formatUKPhoneNumber(to);
  const typeName =
    certificateType === "EIC"
      ? "Electrical Installation Certificate"
      : "Electrical Installation Condition Report";

  const caption = `${typeName} for ${address} — generated by CertMate`;

  const url = `${BASE_URL}/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`;

  const payload = {
    messaging_product: "whatsapp",
    recipient_type: "individual",
    to: formatted.replace("+", ""), // WhatsApp API expects number without +
    type: "document",
    document: {
      link: mediaUrl,
      caption,
      filename: `${certificateType}_${address.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`,
    },
  };

  logger.info("Sending WhatsApp message", {
    to: formatted,
    address,
    certificateType,
  });

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.WHATSAPP_TOKEN}`,
    },
    body: JSON.stringify(payload),
  });

  const data = await response.json();

  if (!response.ok) {
    const errorMsg = data?.error?.message || JSON.stringify(data);
    logger.error("WhatsApp API error", {
      status: response.status,
      error: errorMsg,
      to: formatted,
    });
    throw new Error(`WhatsApp API error: ${errorMsg}`);
  }

  logger.info("WhatsApp message sent", {
    messageId: data?.messages?.[0]?.id,
    to: formatted,
  });

  return data;
}
