import type { Metadata, Viewport } from 'next';
import { Toaster } from 'sonner';
import { InstallPromptProvider } from '@/components/pwa/install-prompt-provider';
import { SwUpdateProvider } from '@/components/pwa/sw-update-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'CertMate — EICR-oMatic',
  description: 'Voice-driven EICR / EIC certificate authoring',
  applicationName: 'CertMate',
  // `icons` makes Next emit <link rel="icon"> + <link rel="apple-touch-icon">
  // pointing at the files generated by `scripts/generate-pwa-icons.mjs`.
  // Keeping these explicit (rather than relying on `src/app/icon.tsx`
  // conventions) means the raster assets live in `public/` and are served
  // unhashed with the SW's CacheFirst "icons" rule applied.
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/apple-icon-180.png', sizes: '180x180', type: 'image/png' }],
  },
  appleWebApp: {
    capable: true,
    title: 'CertMate',
    statusBarStyle: 'black-translucent',
  },
  formatDetection: {
    telephone: false,
    email: false,
    address: false,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // D9 / WCAG 1.4.4 — pinch-zoom MUST remain available. The previous
  // `maximumScale: 1` + `userScalable: false` combo prevented users
  // (notably low-vision inspectors) from zooming to read small
  // certificate data, and is the canonical example cited by WebAIM for
  // a WCAG 1.4.4 failure. iOS Safari's native font-boost handling plus
  // our own 16 px minimum input font-size (prevents the auto-zoom-on-
  // focus behaviour that was the original excuse for disabling zoom)
  // mean we can safely allow user scaling with no UX regression.
  // If, in testing on a real device, we see the iOS form-field auto-
  // zoom re-emerge (inputs < 16 px font-size re-trigger it), fix the
  // input font-size — do NOT re-disable zoom.
  viewportFit: 'cover',
  // Aligned with `manifest.theme_color` and `surface-0` (`#0a0a0a`) so the
  // iOS status-bar tint, Android task-switcher card, and the app's top
  // edge are all the exact same shade. Previously `#0A0A0F`, which drifted
  // from both the manifest and the design-system token.
  themeColor: '#0a0a0a',
  colorScheme: 'dark',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-dvh bg-[var(--color-surface-0)] text-[var(--color-text-primary)] antialiased">
        {/*
         * Mounted at the root so Chrome's `beforeinstallprompt` is captured
         * the moment the page loads — even on /login, before the user has
         * signed in. Renders nothing; only attaches/cleans up listeners.
         * Serwist auto-registers the service worker itself (see next.config.ts).
         */}
        <InstallPromptProvider />
        {/*
         * Watches the active SW registration for a waiting new version.
         * When one appears, renders a persistent sonner toast with a
         * Reload action. Tap → postMessage `SKIP_WAITING` → `controllerchange`
         * → reload once. See `sw-update-provider.tsx` for the full flow and
         * why this replaces Phase 7a's `skipWaiting: true`. Renders nothing.
         */}
        <SwUpdateProvider />
        {children}
        {/*
         * `richColors` gives info/success/warning/error toasts their own
         * accent without needing per-call styling; for the bare
         * `toast('New version available', ...)` call we rely on the default
         * dark theme. Bottom-right keeps the toast clear of the mobile
         * AppShell bottom nav and the RecordingOverlay mini-pill.
         */}
        <Toaster position="bottom-right" theme="dark" richColors closeButton />
      </body>
    </html>
  );
}
