import type { Metadata, Viewport } from 'next';
import { InstallPromptProvider } from '@/components/pwa/install-prompt-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'CertMate — EICR-oMatic',
  description: 'Voice-driven EICR / EIC certificate authoring',
  applicationName: 'CertMate',
  // `icons` makes Next emit <link rel="icon"> + <link rel="apple-touch-icon">
  // pointing at the files generated by `scripts/generate-pwa-icons.mjs`.
  // Keeping these explicit (rather than relying on `src/app/icon.tsx`
  // conventions) means the raster assets live in `public/` and are served
  // unhashed with the SW's CacheFirst "icons" rule applied.
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/apple-icon-180.png', sizes: '180x180', type: 'image/png' }],
  },
  appleWebApp: {
    capable: true,
    title: 'CertMate',
    statusBarStyle: 'black-translucent',
  },
  formatDetection: {
    telephone: false,
    email: false,
    address: false,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  // Aligned with `manifest.theme_color` and `surface-0` (`#0a0a0a`) so the
  // iOS status-bar tint, Android task-switcher card, and the app's top
  // edge are all the exact same shade. Previously `#0A0A0F`, which drifted
  // from both the manifest and the design-system token.
  themeColor: '#0a0a0a',
  colorScheme: 'dark',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-dvh bg-[var(--color-surface-0)] text-[var(--color-text-primary)] antialiased">
        {/*
         * Mounted at the root so Chrome's `beforeinstallprompt` is captured
         * the moment the page loads — even on /login, before the user has
         * signed in. Renders nothing; only attaches/cleans up listeners.
         * Serwist auto-registers the service worker itself (see next.config.ts).
         */}
        <InstallPromptProvider />
        {children}
      </body>
    </html>
  );
}
